# -*- coding: utf-8 -*-
"""Page data: export.html — Factory-Direct Global Export (源头工厂全球出口), 11 languages."""
from html import escape

CFG = {
    'file': 'export.html',
    'cta2_href': 'https://ouzcable.com/quality.html',
    'title': '35kV Cable Factory-Direct Global Export | Source Factory No Middlemen — OUZHI Cable 欧智电缆 | 35KV电缆源头工厂直供出口',
    'desc': 'Buy 26/35 kV XLPE medium-voltage cables direct from the source factory. OUZHI Cable (欧智电缆): own production lines, full export documentation, EAC/CE/IEC/GOST compliance, multimodal delivery to Central Asia, Middle East, Russia, Europe and Americas — Uzbekistan, Kazakhstan, Turkey, Germany, Malaysia, Mexico. Contact: info@ouzcable.com | +998 99 851 6999.',
    'keywords': 'cable factory direct, 35kV cable export, 35KV电缆源头工厂, source factory cable, cable manufacturer China export, no middlemen cable, EAC certified cable export, GOST 31996 cable export, IEC 60502-2 cable supplier, MV cable exporter Uzbekistan, cable wholesale Kazakhstan, cable import Turkey, Germany MV cable import, cable OEM ODM, OUZHI Cable, 欧智电缆, factory direct quotation',
    'ld_headline': '35 kV Cable Factory-Direct Global Export — OUZHI Cable Source Factory',
    'ld_desc': 'Factory-direct 26/35 kV XLPE medium-voltage cables with full export documentation, EAC/CE compliance and multimodal delivery to 40+ countries. Contact info@ouzcable.com | +998 99 851 6999.',
    'sections': [
        {'type': 'hero'},
        {'type': 'cards', 'title': 's1.title', 'p': 's1.p', 'c': 's1.c'},
        {'type': 'table', 'title': 's2.title', 'p': 's2.p', 'th': 's2.th', 'cols': 4, 'rows': [
            ['s2.r1c1', 's2.r1c2', 's2.r1c3', 's2.r1c4'],
            ['s2.r2c1', 's2.r2c2', 's2.r2c3', 's2.r2c4'],
            ['s2.r3c1', 's2.r3c2', 's2.r3c3', 's2.r3c4'],
            ['s2.r4c1', 's2.r4c2', 's2.r4c3', 's2.r4c4'],
            ['s2.r5c1', 's2.r5c2', 's2.r5c3', 's2.r5c4'],
        ]},
        {'type': 'steps', 'title': 's3.title', 'p': 's3.p', 's': 's3.s', 'n': 5},
        {'type': 'faq', 'title': 'faq.title', 'n': 5},
        {'type': 'cta'}
    ],
}

I18N = {}

I18N['en'] = {
    'hero.eyebrow': 'Factory-Direct · Global Export · 2026',
    'hero.title': '35 kV Cables <span class="accent">Straight from the Source Factory</span> — No Middlemen',
    'hero.sub': 'OUZHI Cable (欧智电缆) — China Source Factory · Export Worldwide',
    'hero.lead': 'Buy 26/35 kV XLPE medium-voltage cables directly from the manufacturer. Own production lines, full export documentation, EAC/CE compliance and multimodal delivery to Central Asia, the Middle East, Russia, Europe and the Americas.',
    'hero.cta1': 'Get Factory Price', 'hero.cta2': 'View Certifications',
    's1.title': 'Why Buy Direct from the Source Factory?',
    's1.p': 'Factory-direct purchasing removes the middleman margin, shortens lead times and guarantees that every drum is manufactured, tested and documented by the same certified plant.',
    's1.c1t': 'True Factory-Direct Pricing', 's1.c1d': 'Quotations are issued directly by the manufacturer — transparent pricing with no trader markups at any stage.',
    's1.c2t': 'Own Production Lines', 's1.c2d': 'Conducting, insulating, armouring and sheathing are all done in-house, so quality and schedule stay under our control.',
    's1.c3t': 'Full Export Documentation', 's1.c3d': 'Certificates of quality, test reports, packing lists, invoices and customs paperwork prepared for your destination market.',
    's1.c4t': 'EAC / CE / IEC Compliance', 's1.c4d': 'Production meets IEC 60502-2, GOST 31996 and GB/T 12706, with EAC and CE documentation support for target regions.',
    's2.title': 'Export Markets & Delivery Options',
    's2.p': 'Serving 40+ countries across five regions — with a delivery mode matched to your project and site access.',
    's2.th1': 'Region', 's2.th2': 'Key Markets', 's2.th3': 'Delivery Mode', 's2.th4': 'Documentation',
    's2.r1c1': 'Central Asia', 's2.r1c2': 'Uzbekistan, Kazakhstan, Mongolia', 's2.r1c3': 'Rail & road', 's2.r1c4': 'EAC, GOST certificates',
    's2.r2c1': 'Middle East', 's2.r2c2': 'UAE, Saudi Arabia, Turkey', 's2.r2c3': 'Sea & air', 's2.r2c4': 'IEC, CE',
    's2.r3c1': 'Russia & CIS', 's2.r3c2': 'Russia, Ukraine, Belarus', 's2.r3c3': 'Rail', 's2.r3c4': 'EAC, GOST',
    's2.r4c1': 'Europe', 's2.r4c2': 'Germany, France, Spain, Portugal', 's2.r4c3': 'Sea & rail', 's2.r4c4': 'CE, IEC',
    's2.r5c1': 'Americas', 's2.r5c2': 'USA, Mexico, Brazil', 's2.r5c3': 'Sea', 's2.r5c4': 'IEC, UL-compliant docs',
    's3.title': 'How a Factory-Direct Order Works',
    's3.p': 'Five clear steps from your inquiry to the arrival of cable drums at your site.',
    's3.s1t': 'Inquiry & Quotation', 's3.s1d': 'Send cable specification and quantity — receive a factory quotation within 24 hours.',
    's3.s2t': 'Order Confirmation', 's3.s2d': 'Sign the contract, agree payment terms and production schedule.',
    's3.s3t': 'Production & Testing', 's3.s3d': 'Cables manufactured and 100% routine-tested on our own lines.',
    's3.s4t': 'Export & Logistics', 's3.s4d': 'Documentation prepared; drums shipped by rail, road or sea.',
    's3.s5t': 'Delivery & Support', 's3.s5d': 'On-time arrival with installation and jointing guidance.',
    'faq.title': 'FAQ — Factory-Direct Export',
    'faq.q1': 'What is the minimum order quantity?', 'faq.a1': 'No fixed minimum for standard configurations — tell us your project needs and we will advise the most economical drum lengths.',
    'faq.q2': 'What payment terms do you accept?', 'faq.a2': 'T/T, L/C at sight and other agreed terms are available per order — discuss options with our export team.',
    'faq.q3': 'Can you supply under our brand (OEM)?', 'faq.a3': 'Yes — OEM/ODM production with custom marking, printing and packaging is available for distributors and project owners.',
    'faq.q4': 'How are cables packed for export?', 'faq.a4': 'Standard steel or wooden export drums, seaworthy packing with moisture protection, ready for container or open-top shipment.',
    'faq.q5': 'How do I get a fast price indication?', 'faq.a5': 'Email or WhatsApp your voltage, conductor, length and quantity — you will receive an indicative price within one business day.',
    'cta.title': 'Get Your Factory-Direct Quotation',
    'cta.p': 'Send your project details and requirements — our export team will reply within 24 hours with pricing, lead time and delivery options.',
}

I18N['zh'] = {
    'hero.eyebrow': '工厂直供 · 全球出口 · 2026',
    'hero.title': '35kV 电缆 <span class="accent">从源头工厂直达</span> — 无中间商',
    'hero.sub': '欧智电缆（OUZHI Cable）— 中国源头工厂 · 出口全球',
    'hero.lead': '直接向制造商采购 26/35kV XLPE 中压电缆。自有生产线、完整出口单证、EAC/CE 合规，多式联运覆盖中亚、中东、俄罗斯、欧洲与美洲。',
    'hero.cta1': '获取工厂价', 'hero.cta2': '查看认证',
    's1.title': '为什么选择源头工厂直购？',
    's1.p': '工厂直购去除中间商差价、缩短交期，并保证每一盘电缆都由同一家认证工厂制造、检测并出具文件。',
    's1.c1t': '真正的工厂直供价', 's1.c1d': '报价直接来自制造商——全程透明定价，无任何贸易商加价。',
    's1.c2t': '自有生产线', 's1.c2d': '导体、绝缘、铠装、护套全部厂内完成，质量与进度始终可控。',
    's1.c3t': '完整出口单证', 's1.c3d': '质量证书、检测报告、装箱单、发票与报关文件，按目的国要求备齐。',
    's1.c4t': 'EAC / CE / IEC 合规', 's1.c4d': '按 IEC 60502-2、GOST 31996、GB/T 12706 生产，并支持目标区域 EAC 与 CE 文件。',
    's2.title': '出口市场与交付方式',
    's2.p': '服务五大区域 40+ 个国家——交付方式与项目及现场条件匹配。',
    's2.th1': '区域', 's2.th2': '重点市场', 's2.th3': '交付方式', 's2.th4': '单证',
    's2.r1c1': '中亚', 's2.r1c2': '乌兹别克斯坦、哈萨克斯坦、蒙古', 's2.r1c3': '铁路与公路', 's2.r1c4': 'EAC、GOST 证书',
    's2.r2c1': '中东', 's2.r2c2': '阿联酋、沙特、土耳其', 's2.r2c3': '海运与空运', 's2.r2c4': 'IEC、CE',
    's2.r3c1': '俄罗斯与独联体', 's2.r3c2': '俄罗斯、乌克兰、白俄罗斯', 's2.r3c3': '铁路', 's2.r3c4': 'EAC、GOST',
    's2.r4c1': '欧洲', 's2.r4c2': '德国、法国、西班牙、葡萄牙', 's2.r4c3': '海运与铁路', 's2.r4c4': 'CE、IEC',
    's2.r5c1': '美洲', 's2.r5c2': '美国、墨西哥、巴西', 's2.r5c3': '海运', 's2.r5c4': 'IEC、符合 UL 文件',
    's3.title': '工厂直供订单流程',
    's3.p': '从询盘到电缆到场的五个清晰步骤。',
    's3.s1t': '询盘与报价', 's3.s1d': '发送电缆规格与数量——24 小时内获得工厂报价。',
    's3.s2t': '订单确认', 's3.s2d': '签订合同，约定付款方式与生产排程。',
    's3.s3t': '生产与检测', 's3.s3d': '自有生产线制造，每盘出厂前 100% 常规检测。',
    's3.s4t': '出口与物流', 's3.s4d': '单证齐备，铁路、公路或海运发运。',
    's3.s5t': '交付与支持', 's3.s5d': '准时到场，并提供安装与接头指导。',
    'faq.title': '常见问题 — 工厂直供出口',
    'faq.q1': '起订量是多少？', 'faq.a1': '标准配置无固定起订量——告知项目需求，我们将建议最经济的盘长。',
    'faq.q2': '接受哪些付款方式？', 'faq.a2': '支持 T/T、即期信用证等按订单约定的方式——请与出口团队沟通。',
    'faq.q3': '能否贴牌（OEM）供货？', 'faq.a3': '可以。为经销商与项目业主提供 OEM/ODM 生产，含定制标识、印字与包装。',
    'faq.q4': '出口包装是怎样的？', 'faq.a4': '标准钢木出口盘，防潮适航包装，适用于集装箱或敞顶发运。',
    'faq.q5': '如何快速获得价格？', 'faq.a5': '通过邮件或 WhatsApp 告知电压、导体、长度与数量，一个工作日内回复参考价。',
    'cta.title': '获取工厂直供报价',
    'cta.p': '发送项目详情与需求——出口团队将在 24 小时内回复价格、交期与交付方案。',
}

I18N['ru'] = {
    'hero.eyebrow': 'Прямо с завода · Глобальный экспорт · 2026',
    'hero.title': 'Кабели 35 кВ <span class="accent">напрямую с завода-изготовителя</span> — без посредников',
    'hero.sub': 'OUZHI Cable (欧智电缆) — завод-изготовитель в Китае · Экспорт по всему миру',
    'hero.lead': 'Покупайте кабели среднего напряжения 26/35 кВ XLPE напрямую у производителя. Собственные линии, полная экспортная документация, соответствие EAC/CE, мультимодальная доставка в Центральную Азию, на Ближний Восток, в Россию, Европу и Америку.',
    'hero.cta1': 'Получить цену завода', 'hero.cta2': 'Сертификаты',
    's1.title': 'Почему покупать напрямую у завода-изготовителя?',
    's1.p': 'Прямая закупка убирает наценку посредников, сокращает сроки и гарантирует, что каждый барабан изготовлен, протестирован и задокументирован одним сертифицированным заводом.',
    's1.c1t': 'Настоящая цена завода', 's1.c1d': 'Котировки выставляются напрямую производителем — прозрачные цены без торговых наценок.',
    's1.c2t': 'Собственные линии', 's1.c2d': 'Жила, изоляция, броня и оболочка — всё на собственном производстве: качество и сроки под контролем.',
    's1.c3t': 'Полная экспортная документация', 's1.c3d': 'Сертификаты качества, протоколы испытаний, упаковочные листы, инвойсы и таможенные документы для вашего рынка.',
    's1.c4t': 'Соответствие EAC / CE / IEC', 's1.c4d': 'Производство по IEC 60502-2, GOST 31996 и GB/T 12706 с документами EAC и CE для целевых регионов.',
    's2.title': 'Экспортные рынки и варианты доставки',
    's2.p': 'Обслуживаем 40+ стран в пяти регионах — доставка подбирается под ваш проект и площадку.',
    's2.th1': 'Регион', 's2.th2': 'Ключевые рынки', 's2.th3': 'Доставка', 's2.th4': 'Документы',
    's2.r1c1': 'Центральная Азия', 's2.r1c2': 'Узбекистан, Казахстан, Монголия', 's2.r1c3': 'ЖД и авто', 's2.r1c4': 'EAC, сертификаты GOST',
    's2.r2c1': 'Ближний Восток', 's2.r2c2': 'ОАЭ, Саудовская Аравия, Турция', 's2.r2c3': 'Море и воздух', 's2.r2c4': 'IEC, CE',
    's2.r3c1': 'Россия и СНГ', 's2.r3c2': 'Россия, Украина, Беларусь', 's2.r3c3': 'ЖД', 's2.r3c4': 'EAC, GOST',
    's2.r4c1': 'Европа', 's2.r4c2': 'Германия, Франция, Испания, Португалия', 's2.r4c3': 'Море и ЖД', 's2.r4c4': 'CE, IEC',
    's2.r5c1': 'Америка', 's2.r5c2': 'США, Мексика, Бразилия', 's2.r5c3': 'Море', 's2.r5c4': 'IEC, документы по UL',
    's3.title': 'Как работает заказ напрямую с завода',
    's3.p': 'Пять понятных шагов от вашего запроса до прибытия барабанов на объект.',
    's3.s1t': 'Запрос и котировка', 's3.s1d': 'Отправьте спецификацию и количество — котировка завода в течение 24 часов.',
    's3.s2t': 'Подтверждение заказа', 's3.s2d': 'Подпишите контракт, согласуйте условия оплаты и график производства.',
    's3.s3t': 'Производство и испытания', 's3.s3d': 'Изготовление на собственных линиях, 100% контроль каждой партии.',
    's3.s4t': 'Экспорт и логистика', 's3.s4d': 'Подготовка документов; отгрузка ЖД, авто или морем.',
    's3.s5t': 'Поставка и поддержка', 's3.s5d': 'Своевременная доставка с рекомендациями по монтажу и соединению.',
    'faq.title': 'FAQ — экспорт напрямую с завода',
    'faq.q1': 'Каков минимальный объём заказа?', 'faq.a1': 'Для стандартных конфигураций фиксированного минимума нет — укажите потребности, предложим экономичные длины.',
    'faq.q2': 'Какие условия оплаты вы принимаете?', 'faq.a2': 'T/T, аккредитив L/C at sight и другие согласованные условия — обсудите с нашей экспортной командой.',
    'faq.q3': 'Возможно ли производство под нашей маркой (OEM)?', 'faq.a3': 'Да — OEM/ODM с индивидуальной маркировкой, печатью и упаковкой для дистрибьюторов и владельцев проектов.',
    'faq.q4': 'Как упаковываются кабели для экспорта?', 'faq.a4': 'Стандартные стальные или деревянные экспортные барабаны, морская упаковка с защитой от влаги.',
    'faq.q5': 'Как быстро получить цену?', 'faq.a5': 'Пришлите по email или WhatsApp напряжение, сечение, длину и количество — цена в течение одного рабочего дня.',
    'cta.title': 'Получите котировку напрямую с завода',
    'cta.p': 'Отправьте детали проекта — экспортная команда ответит в течение 24 часов с ценой, сроками и вариантами доставки.',
}

I18N['ar'] = {
    'hero.eyebrow': 'مباشرة من المصنع · تصدير عالمي · 2026',
    'hero.title': 'كابلات 35 ك.ف <span class="accent">مباشرة من المصنع المصدر</span> — بدون وسطاء',
    'hero.sub': 'OUZHI Cable (欧智电缆) — مصنع مصدر في الصين · تصدير عالمي',
    'hero.lead': 'اشترِ كابلات الجهد المتوسط 26/35 ك.ف XLPE مباشرة من الشركة المصنعة. خطوط إنتاج خاصة، وثائق تصدير كاملة، امتثال EAC/CE، وتسليم متعدد الوسائط إلى آسيا الوسطى والشرق الأوسط وروسيا وأوروبا والأمريكتين.',
    'hero.cta1': 'احصل على سعر المصنع', 'hero.cta2': 'عرض الشهادات',
    's1.title': 'لماذا الشراء المباشر من المصنع المصدر؟',
    's1.p': 'الشراء المباشر يزيل هامش الوسيط ويقصر المهل ويضمن أن كل بكرة تُصنع وتُختبر وتُوثق في نفس المصنع المعتمد.',
    's1.c1t': 'سعر المصنع الحقيقي', 's1.c1d': 'الأسعار تصدر مباشرة من الشركة المصنعة — شفافية كاملة دون هوامش تجارية.',
    's1.c2t': 'خطوط إنتاج خاصة', 's1.c2d': 'الموصل والعزل والتسليح والغلاف كلها داخل المصنع — الجودة والجدول تحت سيطرتنا.',
    's1.c3t': 'وثائق تصدير كاملة', 's1.c3d': 'شهادات جودة وتقارير اختبار وقوائم تعبئة وفواتير ووثائق جمركية لسوقك.',
    's1.c4t': 'امتثال EAC / CE / IEC', 's1.c4d': 'إنتاج وفق IEC 60502-2 وGOST 31996 وGB/T 12706 مع وثائق EAC وCE للمناطق المستهدفة.',
    's2.title': 'أسواق التصدير وخيارات التسليم',
    's2.p': 'خدمة أكثر من 40 دولة في خمس مناطق — بطريقة تسليم تناسب مشروعك وموقعك.',
    's2.th1': 'المنطقة', 's2.th2': 'الأسواق الرئيسية', 's2.th3': 'طريقة التسليم', 's2.th4': 'الوثائق',
    's2.r1c1': 'آسيا الوسطى', 's2.r1c2': 'أوزبكستان، كازاخستان، منغوليا', 's2.r1c3': 'سكة حديد وطرق', 's2.r1c4': 'شهادات EAC وGOST',
    's2.r2c1': 'الشرق الأوسط', 's2.r2c2': 'الإمارات، السعودية، تركيا', 's2.r2c3': 'بحر وجو', 's2.r2c4': 'IEC، CE',
    's2.r3c1': 'روسيا ورابطة الدول', 's2.r3c2': 'روسيا، أوكرانيا، بيلاروسيا', 's2.r3c3': 'سكة حديد', 's2.r3c4': 'EAC، GOST',
    's2.r4c1': 'أوروبا', 's2.r4c2': 'ألمانيا، فرنسا، إسبانيا، البرتغال', 's2.r4c3': 'بحر وسكة حديد', 's2.r4c4': 'CE، IEC',
    's2.r5c1': 'الأمريكتان', 's2.r5c2': 'الولايات المتحدة، المكسيك، البرازيل', 's2.r5c3': 'بحر', 's2.r5c4': 'IEC، وثائق متوافقة مع UL',
    's3.title': 'كيف تعمل الطلبات المباشرة من المصنع',
    's3.p': 'خمس خطوات واضحة من استفسارك حتى وصول البراميل إلى موقعك.',
    's3.s1t': 'الاستفسار والسعر', 's3.s1d': 'أرسل المواصفات والكمية — سعر المصنع خلال 24 ساعة.',
    's3.s2t': 'تأكيد الطلب', 's3.s2d': 'وقّع العقد واتفق على شروط الدفع وجدول الإنتاج.',
    's3.s3t': 'الإنتاج والاختبار', 's3.s3d': 'تصنيع على خطوطنا واختبار 100% لكل بكرة.',
    's3.s4t': 'التصدير واللوجستيات', 's3.s4d': 'إعداد الوثائق؛ شحن بالقطار أو الطرق أو البحر.',
    's3.s5t': 'التسليم والدعم', 's3.s5d': 'وصول في الوقت المحدد مع إرشادات التركيب والتوصيل.',
    'faq.title': 'الأسئلة الشائعة — التصدير المباشر من المصنع',
    'faq.q1': 'ما هو الحد الأدنى للطلب؟', 'faq.a1': 'لا حد أدنى ثابت للتكوينات القياسية — أخبرنا باحتياجاتك ونقترح أطوال البراميل الاقتصادية.',
    'faq.q2': 'ما شروط الدفع المقبولة؟', 'faq.a2': 'T/T، اعتماد مستندي L/C عند الاطلاع وشروط أخرى متفق عليها — ناقشها مع فريق التصدير.',
    'faq.q3': 'هل يمكن التوريد بعلامتنا التجارية (OEM)؟', 'faq.a3': 'نعم — إنتاج OEM/ODM بعلامات وطباعة وتغليف مخصص للموزعين وأصحاب المشاريع.',
    'faq.q4': 'كيف تُعبأ الكابلات للتصدير؟', 'faq.a4': 'براميل تصدير قياسية من الفولاذ أو الخشب، تغليف بحري محمي من الرطوبة.',
    'faq.q5': 'كيف أحصل على سعر سريع؟', 'faq.a5': 'أرسل بالبريد أو واتساب الجهد والمقطع والطول والكمية — سعر استرشادي خلال يوم عمل.',
    'cta.title': 'احصل على عرض أسعارك المباشر من المصنع',
    'cta.p': 'أرسل تفاصيل مشروعك — يرد فريق التصدير خلال 24 ساعة بالسعر والمهلة وخيارات التسليم.',
}

I18N['fr'] = {
    'hero.eyebrow': 'Direct usine · Export mondial · 2026',
    'hero.title': 'Câbles 35 kV <span class="accent">directement de l\u2019usine source</span> — sans intermédiaires',
    'hero.sub': 'OUZHI Cable (欧智电缆) — usine source en Chine · Export mondial',
    'hero.lead': 'Achetez des câbles moyenne tension 26/35 kV XLPE directement auprès du fabricant. Lignes de production propres, documentation export complète, conformité EAC/CE et livraison multimodale vers l\u2019Asie centrale, le Moyen-Orient, la Russie, l\u2019Europe et les Amériques.',
    'hero.cta1': 'Obtenir un prix usine', 'hero.cta2': 'Voir les certifications',
    's1.title': 'Pourquoi acheter directement à l\u2019usine source ?',
    's1.p': 'L\u2019achat direct supprime la marge des intermédiaires, raccourcit les délais et garantit que chaque touret est fabriqué, testé et documenté par la même usine certifiée.',
    's1.c1t': 'Vrai prix d\u2019usine', 's1.c1d': 'Devis émis directement par le fabricant — prix transparents sans marges de négoce.',
    's1.c2t': 'Lignes de production propres', 's1.c2d': 'Conducteur, isolation, armure et gaine réalisés en interne — qualité et délais sous contrôle.',
    's1.c3t': 'Documentation export complète', 's1.c3d': 'Certificats de qualité, rapports d\u2019essais, listes de colisage, factures et douane préparés pour votre marché.',
    's1.c4t': 'Conformité EAC / CE / IEC', 's1.c4d': 'Production selon IEC 60502-2, GOST 31996 et GB/T 12706, avec documents EAC et CE.',
    's2.title': 'Marchés export et options de livraison',
    's2.p': 'Plus de 40 pays dans cinq régions — un mode de livraison adapté à votre projet.',
    's2.th1': 'Région', 's2.th2': 'Marchés clés', 's2.th3': 'Mode de livraison', 's2.th4': 'Documentation',
    's2.r1c1': 'Asie centrale', 's2.r1c2': 'Ouzbékistan, Kazakhstan, Mongolie', 's2.r1c3': 'Rail et route', 's2.r1c4': 'Certificats EAC, GOST',
    's2.r2c1': 'Moyen-Orient', 's2.r2c2': 'EAU, Arabie saoudite, Turquie', 's2.r2c3': 'Mer et air', 's2.r2c4': 'IEC, CE',
    's2.r3c1': 'Russie et CEI', 's2.r3c2': 'Russie, Ukraine, Biélorussie', 's2.r3c3': 'Rail', 's2.r3c4': 'EAC, GOST',
    's2.r4c1': 'Europe', 's2.r4c2': 'Allemagne, France, Espagne, Portugal', 's2.r4c3': 'Mer et rail', 's2.r4c4': 'CE, IEC',
    's2.r5c1': 'Amériques', 's2.r5c2': 'États-Unis, Mexique, Brésil', 's2.r5c3': 'Mer', 's2.r5c4': 'IEC, docs conformes UL',
    's3.title': 'Comment fonctionne une commande directe usine',
    's3.p': 'Cinq étapes claires, de votre demande à l\u2019arrivée des tourets sur site.',
    's3.s1t': 'Demande et devis', 's3.s1d': 'Envoyez spécification et quantité — devis usine sous 24 h.',
    's3.s2t': 'Confirmation de commande', 's3.s2d': 'Signez le contrat, convenez des conditions de paiement et du planning.',
    's3.s3t': 'Production et essais', 's3.s3d': 'Fabrication sur nos lignes, 100% contrôlé.',
    's3.s4t': 'Export et logistique', 's3.s4d': 'Documents préparés ; expédition rail, route ou mer.',
    's3.s5t': 'Livraison et support', 's3.s5d': 'Arrivée à temps avec conseils d\u2019installation et de jonction.',
    'faq.title': 'FAQ — export direct usine',
    'faq.q1': 'Quantité minimale ?', 'faq.a1': 'Pas de minimum fixe pour les configurations standard — indiquez vos besoins pour des longueurs économiques.',
    'faq.q2': 'Quelles conditions de paiement ?', 'faq.a2': 'T/T, L/C à vue et autres conditions convenues — discutez avec notre équipe export.',
    'faq.q3': 'Fourniture sous votre marque (OEM) ?', 'faq.a3': 'Oui — production OEM/ODM avec marquage, impression et emballage personnalisés.',
    'faq.q4': 'Emballage export ?', 'faq.a4': 'Tourets acier ou bois, emballage maritime avec protection contre l\u2019humidité.',
    'faq.q5': 'Comment obtenir un prix rapide ?', 'faq.a5': 'Email ou WhatsApp : tension, section, longueur, quantité — prix indicatif sous un jour ouvré.',
    'cta.title': 'Obtenez votre devis direct usine',
    'cta.p': 'Envoyez les détails de votre projet — réponse sous 24 h avec prix, délai et options de livraison.',
}

I18N['de'] = {
    'hero.eyebrow': 'Direkt ab Werk · Globaler Export · 2026',
    'hero.title': '35-kV-Kabel <span class="accent">direkt vom Quellenwerk</span> — ohne Zwischenhändler',
    'hero.sub': 'OUZHI Cable (欧智电缆) — Quellenwerk in China · Export weltweit',
    'hero.lead': 'Kaufen Sie 26/35-kV-XLPE-Mittelspannungskabel direkt beim Hersteller. Eigene Produktionslinien, vollständige Exportdokumentation, EAC/CE-Konformität und multimodale Lieferung nach Zentralasien, in den Nahen Osten, nach Russland, Europa und Amerika.',
    'hero.cta1': 'Werkspreis erhalten', 'hero.cta2': 'Zertifikate ansehen',
    's1.title': 'Warum direkt beim Quellenwerk kaufen?',
    's1.p': 'Direktkauf entfernt die Händlermarge, verkürzt Lieferzeiten und garantiert, dass jede Trommel vom selben zertifizierten Werk gefertigt, geprüft und dokumentiert wird.',
    's1.c1t': 'Echter Werkspreis', 's1.c1d': 'Angebote direkt vom Hersteller — transparente Preise ohne Händleraufschläge.',
    's1.c2t': 'Eigene Produktionslinien', 's1.c2d': 'Leiter, Isolierung, Bewehrung und Mantel im Haus — Qualität und Termine unter Kontrolle.',
    's1.c3t': 'Vollständige Exportdokumentation', 's1.c3d': 'Qualitätszertifikate, Prüfberichte, Packlisten, Rechnungen und Zolldokumente für Ihren Markt.',
    's1.c4t': 'EAC-/CE-/IEC-Konformität', 's1.c4d': 'Produktion nach IEC 60502-2, GOST 31996 und GB/T 12706 mit EAC- und CE-Dokumenten.',
    's2.title': 'Exportmärkte und Lieferoptionen',
    's2.p': 'Über 40 Länder in fünf Regionen — Lieferart passend zu Projekt und Standort.',
    's2.th1': 'Region', 's2.th2': 'Kernmärkte', 's2.th3': 'Lieferart', 's2.th4': 'Dokumentation',
    's2.r1c1': 'Zentralasien', 's2.r1c2': 'Usbekistan, Kasachstan, Mongolei', 's2.r1c3': 'Bahn und Straße', 's2.r1c4': 'EAC-, GOST-Zertifikate',
    's2.r2c1': 'Naher Osten', 's2.r2c2': 'VAE, Saudi-Arabien, Türkei', 's2.r2c3': 'See und Luft', 's2.r2c4': 'IEC, CE',
    's2.r3c1': 'Russland & GUS', 's2.r3c2': 'Russland, Ukraine, Belarus', 's2.r3c3': 'Bahn', 's2.r3c4': 'EAC, GOST',
    's2.r4c1': 'Europa', 's2.r4c2': 'Deutschland, Frankreich, Spanien, Portugal', 's2.r4c3': 'See und Bahn', 's2.r4c4': 'CE, IEC',
    's2.r5c1': 'Amerika', 's2.r5c2': 'USA, Mexiko, Brasilien', 's2.r5c3': 'See', 's2.r5c4': 'IEC, UL-konforme Dokumente',
    's3.title': 'So funktioniert eine Bestellung direkt ab Werk',
    's3.p': 'Fünf klare Schritte von Ihrer Anfrage bis zur Ankunft der Trommeln am Standort.',
    's3.s1t': 'Anfrage und Angebot', 's3.s1d': 'Senden Sie Spezifikation und Menge — Werksangebot innerhalb von 24 Stunden.',
    's3.s2t': 'Auftragsbestätigung', 's3.s2d': 'Vertrag unterzeichnen, Zahlungsbedingungen und Produktionsplan vereinbaren.',
    's3.s3t': 'Produktion und Prüfung', 's3.s3d': 'Fertigung auf eigenen Linien, 100% geprüft.',
    's3.s4t': 'Export und Logistik', 's3.s4d': 'Dokumente vorbereitet; Versand per Bahn, Straße oder See.',
    's3.s5t': 'Lieferung und Support', 's3.s5d': 'Pünktliche Ankunft mit Installations- und Muffenanleitung.',
    'faq.title': 'FAQ — Export direkt ab Werk',
    'faq.q1': 'Mindestbestellmenge?', 'faq.a1': 'Kein festes Minimum für Standardkonfigurationen — nennen Sie Ihren Bedarf für wirtschaftliche Trommellängen.',
    'faq.q2': 'Welche Zahlungsbedingungen?', 'faq.a2': 'T/T, L/C at sight und andere vereinbarte Bedingungen — besprechen Sie mit unserem Exportteam.',
    'faq.q3': 'Lieferung unter eigener Marke (OEM)?', 'faq.a3': 'Ja — OEM/ODM mit kundenspezifischer Kennzeichnung, Bedruckung und Verpackung.',
    'faq.q4': 'Exportverpackung?', 'faq.a4': 'Standard-Exporttrommeln aus Stahl oder Holz, seetüchtige Verpackung mit Feuchtigkeitsschutz.',
    'faq.q5': 'Wie erhalte ich schnell einen Preis?', 'faq.a5': 'E-Mail oder WhatsApp: Spannung, Querschnitt, Länge, Menge — Richtpreis innerhalb eines Werktags.',
    'cta.title': 'Erhalten Sie Ihr Werksangebot',
    'cta.p': 'Senden Sie Ihre Projektdaten — Antwort innerhalb von 24 Stunden mit Preis, Lieferzeit und Optionen.',
}

I18N['uk'] = {
    'hero.eyebrow': 'Напряму з заводу · Глобальний експорт · 2026',
    'hero.title': 'Кабелі 35 кВ <span class="accent">напряму з заводу-виробника</span> — без посередників',
    'hero.sub': 'OUZHI Cable (欧智电缆) — завод-виробник у Китаї · Експорт по всьому світу',
    'hero.lead': 'Купуйте кабелі середньої напруги 26/35 кВ XLPE напряму у виробника. Власні лінії, повна експортна документація, відповідність EAC/CE, мультимодальна доставка в Центральну Азію, на Близький Схід, у Росію, Європу та Америку.',
    'hero.cta1': 'Отримати ціну заводу', 'hero.cta2': 'Переглянути сертифікати',
    's1.title': 'Чому купувати напряму у заводу-виробника?',
    's1.p': 'Пряма закупівля прибирає націнку посередників, скорочує терміни та гарантує, що кожен барабан виготовлено, протестовано та задокументовано одним сертифікованим заводом.',
    's1.c1t': 'Справжня ціна заводу', 's1.c1d': 'Котирування виставляє безпосередньо виробник — прозорі ціни без торгових націнок.',
    's1.c2t': 'Власні виробничі лінії', 's1.c2d': 'Жила, ізоляція, броня та оболонка — все на власному виробництві: якість і строки під контролем.',
    's1.c3t': 'Повна експортна документація', 's1.c3d': 'Сертифікати якості, протоколи випробувань, пакувальні листи, інвойси та митні документи для вашого ринку.',
    's1.c4t': 'Відповідність EAC / CE / IEC', 's1.c4d': 'Виробництво за IEC 60502-2, GOST 31996 та GB/T 12706 з документами EAC і CE для цільових регіонів.',
    's2.title': 'Експортні ринки та варіанти доставки',
    's2.p': 'Обслуговуємо 40+ країн у п\u2019яти регіонах — спосіб доставки підбираємо під проєкт і майданчик.',
    's2.th1': 'Регіон', 's2.th2': 'Ключові ринки', 's2.th3': 'Доставка', 's2.th4': 'Документи',
    's2.r1c1': 'Центральна Азія', 's2.r1c2': 'Узбекистан, Казахстан, Монголія', 's2.r1c3': 'Залізниця та авто', 's2.r1c4': 'EAC, сертифікати GOST',
    's2.r2c1': 'Близький Схід', 's2.r2c2': 'ОАЕ, Саудівська Аравія, Туреччина', 's2.r2c3': 'Море та повітря', 's2.r2c4': 'IEC, CE',
    's2.r3c1': 'Росія та СНД', 's2.r3c2': 'Росія, Україна, Білорусь', 's2.r3c3': 'Залізниця', 's2.r3c4': 'EAC, GOST',
    's2.r4c1': 'Європа', 's2.r4c2': 'Німеччина, Франція, Іспанія, Португалія', 's2.r4c3': 'Море та залізниця', 's2.r4c4': 'CE, IEC',
    's2.r5c1': 'Америка', 's2.r5c2': 'США, Мексика, Бразилія', 's2.r5c3': 'Море', 's2.r5c4': 'IEC, документи за UL',
    's3.title': 'Як працює замовлення напряму з заводу',
    's3.p': 'П\u2019ять зрозумілих кроків від вашого запиту до прибуття барабанів на об\u2019єкт.',
    's3.s1t': 'Запит і котирування', 's3.s1d': 'Надішліть специфікацію та кількість — котирування заводу протягом 24 годин.',
    's3.s2t': 'Підтвердження замовлення', 's3.s2d': 'Підпишіть контракт, узгодьте умови оплати та графік виробництва.',
    's3.s3t': 'Виробництво та випробування', 's3.s3d': 'Виготовлення на власних лініях, 100% контроль кожної партії.',
    's3.s4t': 'Експорт і логістика', 's3.s4d': 'Підготовка документів; відвантаження залізницею, авто або морем.',
    's3.s5t': 'Поставка та підтримка', 's3.s5d': 'Своєчасна доставка з рекомендаціями з монтажу та з\u2019єднання.',
    'faq.title': 'Питання та відповіді — експорт напряму з заводу',
    'faq.q1': 'Який мінімальний обсяг замовлення?', 'faq.a1': 'Для стандартних конфігурацій фіксованого мінімуму немає — вкажіть потреби, запропонуємо економні довжини.',
    'faq.q2': 'Які умови оплати?', 'faq.a2': 'T/T, акредитив L/C at sight та інші узгоджені умови — обговоріть з експортною командою.',
    'faq.q3': 'Чи можливе виробництво під нашою маркою (OEM)?', 'faq.a3': 'Так — OEM/ODM з індивідуальним маркуванням, друком та упаковкою для дистриб\u2019юторів і власників проєктів.',
    'faq.q4': 'Як пакуються кабелі для експорту?', 'faq.a4': 'Стандартні сталеві або дерев\u2019яні експортні барабани, морська упаковка із захистом від вологи.',
    'faq.q5': 'Як швидко отримати ціну?', 'faq.a5': 'Надішліть email або WhatsApp напругу, переріз, довжину та кількість — ціна протягом одного робочого дня.',
    'cta.title': 'Отримайте котирування напряму з заводу',
    'cta.p': 'Надішліть деталі проєкту — експортна команда відповість протягом 24 годин з ціною, термінами та варіантами доставки.',
}

I18N['es'] = {
    'hero.eyebrow': 'Directo de fábrica · Exportación global · 2026',
    'hero.title': 'Cables de 35 kV <span class="accent">directo de la fábrica de origen</span> — sin intermediarios',
    'hero.sub': 'OUZHI Cable (欧智电缆) — fábrica de origen en China · Exportación mundial',
    'hero.lead': 'Compre cables de media tensión 26/35 kV XLPE directamente del fabricante. Líneas de producción propias, documentación de exportación completa, cumplimiento EAC/CE y entrega multimodal a Asia Central, Medio Oriente, Rusia, Europa y las Américas.',
    'hero.cta1': 'Obtener precio de fábrica', 'hero.cta2': 'Ver certificaciones',
    's1.title': '¿Por qué comprar directo a la fábrica de origen?',
    's1.p': 'La compra directa elimina el margen del intermediario, acorta plazos y garantiza que cada bobina sea fabricada, probada y documentada por la misma planta certificada.',
    's1.c1t': 'Precio real de fábrica', 's1.c1d': 'Cotizaciones emitidas directamente por el fabricante — precios transparentes sin recargos comerciales.',
    's1.c2t': 'Líneas de producción propias', 's1.c2d': 'Conductor, aislamiento, armadura y cubierta — todo en casa, con calidad y plazos bajo control.',
    's1.c3t': 'Documentación de exportación completa', 's1.c3d': 'Certificados de calidad, informes de ensayo, listas de empaque, facturas y aduanas para su mercado.',
    's1.c4t': 'Cumplimiento EAC / CE / IEC', 's1.c4d': 'Producción según IEC 60502-2, GOST 31996 y GB/T 12706, con documentación EAC y CE.',
    's2.title': 'Mercados de exportación y opciones de entrega',
    's2.p': 'Sirviendo a más de 40 países en cinco regiones — con un modo de entrega acorde a su proyecto.',
    's2.th1': 'Región', 's2.th2': 'Mercados clave', 's2.th3': 'Modo de entrega', 's2.th4': 'Documentación',
    's2.r1c1': 'Asia Central', 's2.r1c2': 'Uzbekistán, Kazajistán, Mongolia', 's2.r1c3': 'Ferrocarril y carretera', 's2.r1c4': 'Certificados EAC, GOST',
    's2.r2c1': 'Medio Oriente', 's2.r2c2': 'EAU, Arabia Saudita, Turquía', 's2.r2c3': 'Mar y aire', 's2.r2c4': 'IEC, CE',
    's2.r3c1': 'Rusia y CEI', 's2.r3c2': 'Rusia, Ucrania, Bielorrusia', 's2.r3c3': 'Ferrocarril', 's2.r3c4': 'EAC, GOST',
    's2.r4c1': 'Europa', 's2.r4c2': 'Alemania, Francia, España, Portugal', 's2.r4c3': 'Mar y ferrocarril', 's2.r4c4': 'CE, IEC',
    's2.r5c1': 'Américas', 's2.r5c2': 'EE. UU., México, Brasil', 's2.r5c3': 'Mar', 's2.r5c4': 'IEC, documentos conformes a UL',
    's3.title': 'Cómo funciona un pedido directo de fábrica',
    's3.p': 'Cinco pasos claros, de su consulta a la llegada de bobinas a su sitio.',
    's3.s1t': 'Consulta y cotización', 's3.s1d': 'Envíe especificación y cantidad — cotización de fábrica en 24 horas.',
    's3.s2t': 'Confirmación de pedido', 's3.s2d': 'Firme el contrato, acuerde pagos y cronograma de producción.',
    's3.s3t': 'Producción y ensayos', 's3.s3d': 'Fabricación en nuestras líneas, 100% controlado.',
    's3.s4t': 'Exportación y logística', 's3.s4d': 'Documentos preparados; envío por ferrocarril, carretera o mar.',
    's3.s5t': 'Entrega y soporte', 's3.s5d': 'Llegada puntual con guía de instalación y empalmes.',
    'faq.title': 'FAQ — exportación directa de fábrica',
    'faq.q1': '¿Cuál es la cantidad mínima?', 'faq.a1': 'Sin mínimo fijo para configuraciones estándar — indique sus necesidades para longitudes económicas.',
    'faq.q2': '¿Qué condiciones de pago aceptan?', 'faq.a2': 'T/T, L/C a la vista y otras condiciones acordadas — converse con nuestro equipo de exportación.',
    'faq.q3': '¿Pueden suministrar bajo nuestra marca (OEM)?', 'faq.a3': 'Sí — producción OEM/ODM con marcado, impresión y empaque personalizados.',
    'faq.q4': '¿Cómo se empacan los cables para exportación?', 'faq.a4': 'Bobinas de exportación de acero o madera, embalaje marítimo con protección contra humedad.',
    'faq.q5': '¿Cómo obtengo un precio rápido?', 'faq.a5': 'Envíe por correo o WhatsApp tensión, sección, longitud y cantidad — precio indicativo en un día hábil.',
    'cta.title': 'Obtenga su cotización directa de fábrica',
    'cta.p': 'Envíe los detalles de su proyecto — respuesta en 24 horas con precio, plazo y opciones de entrega.',
}

I18N['tr'] = {
    'hero.eyebrow': 'Fabrikadan Doğrudan · Küresel İhracat · 2026',
    'hero.title': '35 kV Kablolar <span class="accent">Kaynak Fabrikadan Doğrudan</span> — Aracısız',
    'hero.sub': 'OUZHI Cable (欧智电缆) — Çin Kaynak Fabrikası · Dünya Genelinde İhracat',
    'hero.lead': '26/35 kV XLPE orta gerilim kablolarını doğrudan üreticiden satın alın. Kendi üretim hatları, eksiksiz ihracat dokümantasyonu, EAC/CE uyumluluğu ve Orta Asya, Orta Doğu, Rusya, Avrupa ve Amerika\u2019ya multimodal teslimat.',
    'hero.cta1': 'Fabrika Fiyatı Alın', 'hero.cta2': 'Sertifikaları Görün',
    's1.title': 'Neden Kaynak Fabrikadan Doğrudan Almalı?',
    's1.p': 'Fabrikadan doğrudan alım, aracı marjını ortadan kaldırır, süreleri kısaltır ve her makaranın aynı sertifikalı tesis tarafından üretilip test edilmesini garanti eder.',
    's1.c1t': 'Gerçek Fabrika Fiyatı', 's1.c1d': 'Teklifler doğrudan üreticiden verilir — hiçbir aşamada ticari kar marjı olmadan şeffaf fiyat.',
    's1.c2t': 'Kendi Üretim Hatları', 's1.c2d': 'İletken, izolasyon, zırh ve kılıf tamamen kendi tesisimizde — kalite ve takvim kontrolümüzde.',
    's1.c3t': 'Eksiksiz İhracat Dokümantasyonu', 's1.c3d': 'Kalite sertifikaları, test raporları, paketleme listeleri, faturalar ve gümrük evrakları hedef pazarınıza göre hazırlanır.',
    's1.c4t': 'EAC / CE / IEC Uyumluluğu', 's1.c4d': 'Üretim IEC 60502-2, GOST 31996 ve GB/T 12706 standartlarına uygundur; EAC ve CE dokümantasyonu sağlanır.',
    's2.title': 'İhracat Pazarları ve Teslimat Seçenekleri',
    's2.p': 'Beş bölgede 40+ ülkeye hizmet — projenize ve sahanıza uygun teslimat yöntemiyle.',
    's2.th1': 'Bölge', 's2.th2': 'Kilit Pazarlar', 's2.th3': 'Teslimat Yöntemi', 's2.th4': 'Dokümantasyon',
    's2.r1c1': 'Orta Asya', 's2.r1c2': 'Özbekistan, Kazakistan, Moğolistan', 's2.r1c3': 'Demiryolu ve kara', 's2.r1c4': 'EAC, GOST sertifikaları',
    's2.r2c1': 'Orta Doğu', 's2.r2c2': 'BAE, Suudi Arabistan, Türkiye', 's2.r2c3': 'Deniz ve hava', 's2.r2c4': 'IEC, CE',
    's2.r3c1': 'Rusya ve BDT', 's2.r3c2': 'Rusya, Ukrayna, Belarus', 's2.r3c3': 'Demiryolu', 's2.r3c4': 'EAC, GOST',
    's2.r4c1': 'Avrupa', 's2.r4c2': 'Almanya, Fransa, İspanya, Portekiz', 's2.r4c3': 'Deniz ve demiryolu', 's2.r4c4': 'CE, IEC',
    's2.r5c1': 'Amerika', 's2.r5c2': 'ABD, Meksika, Brezilya', 's2.r5c3': 'Deniz', 's2.r5c4': 'IEC, UL uyumlu belgeler',
    's3.title': 'Fabrikadan Doğrudan Sipariş Nasıl Çalışır',
    's3.p': 'Talebinizden makaraların sahanıza ulaşmasına beş net adım.',
    's3.s1t': 'Talep ve Teklif', 's3.s1d': 'Kablo spesifikasyonunu ve miktarı gönderin — 24 saat içinde fabrika teklifi.',
    's3.s2t': 'Sipariş Onayı', 's3.s2d': 'Sözleşmeyi imzalayın, ödeme koşulları ve üretim takvimini kararlaştırın.',
    's3.s3t': 'Üretim ve Test', 's3.s3d': 'Kendi hatlarımızda üretim, %100 kontrol.',
    's3.s4t': 'İhracat ve Lojistik', 's3.s4d': 'Belgeler hazırlanır; demiryolu, kara veya deniz sevkiyatı.',
    's3.s5t': 'Teslimat ve Destek', 's3.s5d': 'Zamanında varış, kurulum ve ek rehberliğiyle.',
    'faq.title': 'SSS — Fabrikadan Doğrudan İhracat',
    'faq.q1': 'Minimum sipariş miktarı nedir?', 'faq.a1': 'Standart konfigürasyonlar için sabit minimum yoktur — ihtiyaçlarınızı söyleyin, ekonomik makara uzunlukları önerelim.',
    'faq.q2': 'Hangi ödeme koşullarını kabul ediyorsunuz?', 'faq.a2': 'T/T, görüldüğünde L/C ve sipariş bazında kararlaştırılan diğer koşullar — ihracat ekibimizle görüşün.',
    'faq.q3': 'Kendi markamızla tedarik (OEM) mümkün mü?', 'faq.a3': 'Evet — distribütörler ve proje sahipleri için özel markalama, baskı ve paketleme ile OEM/ODM üretim.',
    'faq.q4': 'Kablolar ihracat için nasıl paketlenir?', 'faq.a4': 'Standart çelik veya ahşap ihracat makaraları, nem korumalı denize dayanıklı ambalaj.',
    'faq.q5': 'Hızlı fiyat nasıl alınır?', 'faq.a5': 'E-posta veya WhatsApp ile gerilim, kesit, uzunluk ve miktarı gönderin — bir iş günü içinde gösterge fiyat.',
    'cta.title': 'Fabrikadan Doğrudan Teklifinizi Alın',
    'cta.p': 'Proje detaylarınızı gönderin — ihracat ekibimiz 24 saat içinde fiyat, teslim süresi ve teslimat seçenekleriyle yanıtlar.',
}

I18N['pt'] = {
    'hero.eyebrow': 'Direto da fábrica · Exportação global · 2026',
    'hero.title': 'Cabos de 35 kV <span class="accent">direto da fábrica de origem</span> — sem intermediários',
    'hero.sub': 'OUZHI Cable (欧智电缆) — fábrica de origem na China · Exportação mundial',
    'hero.lead': 'Compre cabos de média tensão 26/35 kV XLPE diretamente do fabricante. Linhas de produção próprias, documentação de exportação completa, conformidade EAC/CE e entrega multimodal para Ásia Central, Oriente Médio, Rússia, Europa e Américas.',
    'hero.cta1': 'Obter preço de fábrica', 'hero.cta2': 'Ver certificações',
    's1.title': 'Por que comprar direto da fábrica de origem?',
    's1.p': 'A compra direta elimina a margem do intermediário, encurta prazos e garante que cada bobina seja fabricada, testada e documentada pela mesma planta certificada.',
    's1.c1t': 'Preço real de fábrica', 's1.c1d': 'Cotações emitidas diretamente pelo fabricante — preços transparentes sem margens comerciais.',
    's1.c2t': 'Linhas de produção próprias', 's1.c2d': 'Condutor, isolação, armadura e cobertura — tudo internamente, com qualidade e prazos sob controle.',
    's1.c3t': 'Documentação de exportação completa', 's1.c3d': 'Certificados de qualidade, relatórios de ensaio, listas de embalagem, faturas e alfândega para o seu mercado.',
    's1.c4t': 'Conformidade EAC / CE / IEC', 's1.c4d': 'Produção conforme IEC 60502-2, GOST 31996 e GB/T 12706, com documentação EAC e CE.',
    's2.title': 'Mercados de exportação e opções de entrega',
    's2.p': 'Atendendo mais de 40 países em cinco regiões — com modal de entrega adequado ao seu projeto.',
    's2.th1': 'Região', 's2.th2': 'Mercados-chave', 's2.th3': 'Modal de entrega', 's2.th4': 'Documentação',
    's2.r1c1': 'Ásia Central', 's2.r1c2': 'Uzbequistão, Cazaquistão, Mongólia', 's2.r1c3': 'Ferrovia e rodovia', 's2.r1c4': 'Certificados EAC, GOST',
    's2.r2c1': 'Oriente Médio', 's2.r2c2': 'EAU, Arábia Saudita, Turquia', 's2.r2c3': 'Mar e ar', 's2.r2c4': 'IEC, CE',
    's2.r3c1': 'Rússia e CEI', 's2.r3c2': 'Rússia, Ucrânia, Bielorrússia', 's2.r3c3': 'Ferrovia', 's2.r3c4': 'EAC, GOST',
    's2.r4c1': 'Europa', 's2.r4c2': 'Alemanha, França, Espanha, Portugal', 's2.r4c3': 'Mar e ferrovia', 's2.r4c4': 'CE, IEC',
    's2.r5c1': 'Américas', 's2.r5c2': 'EUA, México, Brasil', 's2.r5c3': 'Mar', 's2.r5c4': 'IEC, documentos conforme UL',
    's3.title': 'Como funciona um pedido direto de fábrica',
    's3.p': 'Cinco passos claros, da sua consulta à chegada das bobinas ao seu local.',
    's3.s1t': 'Consulta e cotação', 's3.s1d': 'Envie especificação e quantidade — cotação de fábrica em 24 horas.',
    's3.s2t': 'Confirmação do pedido', 's3.s2d': 'Assine o contrato, acorde pagamentos e cronograma de produção.',
    's3.s3t': 'Produção e ensaios', 's3.s3d': 'Fabricação em nossas linhas, 100% controlado.',
    's3.s4t': 'Exportação e logística', 's3.s4d': 'Documentos preparados; envio por ferrovia, rodovia ou mar.',
    's3.s5t': 'Entrega e suporte', 's3.s5d': 'Chegada pontual com guia de instalação e emendas.',
    'faq.title': 'FAQ — exportação direta de fábrica',
    'faq.q1': 'Qual a quantidade mínima?', 'faq.a1': 'Sem mínimo fixo para configurações padrão — informe suas necessidades para comprimentos econômicos.',
    'faq.q2': 'Quais condições de pagamento?', 'faq.a2': 'T/T, L/C à vista e outras condições acordadas — converse com nossa equipe de exportação.',
    'faq.q3': 'Podem fornecer com nossa marca (OEM)?', 'faq.a3': 'Sim — produção OEM/ODM com marcação, impressão e embalagem personalizadas.',
    'faq.q4': 'Como os cabos são embalados para exportação?', 'faq.a4': 'Bobinas de exportação de aço ou madeira, embalagem marítima com proteção contra umidade.',
    'faq.q5': 'Como obter um preço rápido?', 'faq.a5': 'Envie por e-mail ou WhatsApp tensão, seção, comprimento e quantidade — preço indicativo em um dia útil.',
    'cta.title': 'Obtenha sua cotação direta de fábrica',
    'cta.p': 'Envie os detalhes do seu projeto — resposta em 24 horas com preço, prazo e opções de entrega.',
}

I18N['mn'] = {
    'hero.eyebrow': 'Үйлдвэрээс шууд · Дэлхийн экспорт · 2026',
    'hero.title': '35 кВ кабел <span class="accent">эх үүсвэр үйлдвэрээс шууд</span> — зуучлагчгүй',
    'hero.sub': 'OUZHI Cable (欧智电缆) — Хятад эх үүсвэр үйлдвэр · Дэлхий даяар экспорт',
    'hero.lead': '26/35 кВ XLPE дундад хүчдэлийн кабелийг үйлдвэрлэгчээс шууд худалдаж аваарай. Өөрийн үйлдвэрлэлийн шугам, бүрэн экспортын баримт, EAC/CE нийцэл, Төв Ази, Ойрхи Дорнод, Орос, Европ, Америк руу олон төрлийн тээвэр.',
    'hero.cta1': 'Үйлдвэрийн үнэ авах', 'hero.cta2': 'Гэрчилгээг үзэх',
    's1.title': 'Яагаад эх үүсвэр үйлдвэрээс шууд авах вэ?',
    's1.p': 'Үйлдвэрээс шууд авах нь зуучлагчийн ашгийг арилгаж, хугацааг богиносгож, ороомог бүрийг нэг гэрчилгээжсэн үйлдвэрээр үйлдвэрлэж, шалгаж, баримтжуулдаг.',
    's1.c1t': 'Жинхэнэ үйлдвэрийн үнэ', 's1.c1d': 'Үнийн саналыг үйлдвэрлэгч шууд гаргадаг — зуучлагчийн нэмэлтгүй ил тод үнэ.',
    's1.c2t': 'Өөрийн үйлдвэрлэлийн шугам', 's1.c2d': 'Дамжуулагч, изоляц, дэмжлэг, хүрдэл бүгд дотооддоо — чанар, хугацаа бидний хяналтад.',
    's1.c3t': 'Бүрэн экспортын баримт', 's1.c3d': 'Чанарын гэрчилгээ, туршилтын тайлан, савлалтын жагсаалт, нэхэмжлэх, гаалийн баримт таны зах зээлд бэлтгэгдэнэ.',
    's1.c4t': 'EAC / CE / IEC нийцэл', 's1.c4d': 'IEC 60502-2, GOST 31996, GB/T 12706 стандартаар үйлдвэрлэж, EAC болон CE баримтаар дэмжинэ.',
    's2.title': 'Экспортын зах зээл ба хүргэлтийн сонголт',
    's2.p': 'Таван бүс нутагт 40+ улсад үйлчилнэ — таны төсөл, талбайд тохирсон хүргэлтийн аргаар.',
    's2.th1': 'Бүс нутаг', 's2.th2': 'Гол зах зээл', 's2.th3': 'Хүргэлтийн арга', 's2.th4': 'Баримт',
    's2.r1c1': 'Төв Ази', 's2.r1c2': 'Узбекистан, Казахстан, Монгол', 's2.r1c3': 'Төмөр зам ба авто', 's2.r1c4': 'EAC, GOST гэрчилгээ',
    's2.r2c1': 'Ойрхи Дорнод', 's2.r2c2': 'Арабын Нэгдсэн Эмират, Саудын Араб, Турк', 's2.r2c3': 'Далай ба агаар', 's2.r2c4': 'IEC, CE',
    's2.r3c1': 'Орос ба ТУХН', 's2.r3c2': 'Орос, Украйн, Беларусь', 's2.r3c3': 'Төмөр зам', 's2.r3c4': 'EAC, GOST',
    's2.r4c1': 'Европ', 's2.r4c2': 'Герман, Франц, Испани, Португал', 's2.r4c3': 'Далай ба төмөр зам', 's2.r4c4': 'CE, IEC',
    's2.r5c1': 'Америк', 's2.r5c2': 'АНУ, Мексик, Бразил', 's2.r5c3': 'Далай', 's2.r5c4': 'IEC, UL нийцсэн баримт',
    's3.title': 'Үйлдвэрээс шууд захиалга хэрхэн ажилладаг вэ',
    's3.p': 'Таны асуултаас ороомог талбайд хүрэх хүртэл таван тодорхой алхам.',
    's3.s1t': 'Асуулт ба үнэ', 's3.s1d': 'Кабелийн үзүүлэлт, тоо хэмжээгээ илгээнэ үү — 24 цагийн дотор үйлдвэрийн үнэ.',
    's3.s2t': 'Захиалга баталгаажуулах', 's3.s2d': 'Гэрээнд гарын үсэг зурж, төлбөрийн нөхцөл, үйлдвэрлэлийн хуваарийг тохиролцоно.',
    's3.s3t': 'Үйлдвэрлэл ба туршилт', 's3.s3d': 'Өөрийн шугам дээр үйлдвэрлэж, 100% шалгана.',
    's3.s4t': 'Экспорт ба логистик', 's3.s4d': 'Баримт бэлтгэж, төмөр зам, авто эсвэл далайгаар ачуулна.',
    's3.s5t': 'Хүргэлт ба дэмжлэг', 's3.s5d': 'Цаг хугацаанд нь хүргэж, суурилуулалт, холболтын зөвлөгөө өгнө.',
    'faq.title': 'Түгээмэл асуулт — үйлдвэрээс шууд экспорт',
    'faq.q1': 'Хамгийн бага захиалга хэд вэ?', 'faq.a1': 'Стандарт тохиргоонд тогтмол доод хэмжээ байхгүй — хэрэгцээгээ хэлнэ үү, эдийн засгийн ороомгийн уртыг зөвлөнө.',
    'faq.q2': 'Ямар төлбөрийн нөхцөл хүлээн авдаг вэ?', 'faq.a2': 'T/T, үзсэн даруйд L/C болон бусад тохирсон нөхцөл — экспортын багтай ярилцана уу.',
    'faq.q3': 'Өөрийн брэндээр (OEM) нийлүүлэх боломжтой юу?', 'faq.a3': 'Тийм — дистрибьютор, төслийн эзэмшигчдэд зориулж тусгай тэмдэглэгээ, хэвлэл, савлалттай OEM/ODM үйлдвэрлэл.',
    'faq.q4': 'Кабелийг экспортод хэрхэн савладаг вэ?', 'faq.a4': 'Стандарт ган эсвэл модон экспортын ороомог, чийгээс хамгаалсан далайн савлагаа.',
    'faq.q5': 'Хурдан үнийг хэрхэн авах вэ?', 'faq.a5': 'Имэйл эсвэл WhatsApp-аар хүчдэл, утас, урт, тоо хэмжээгээ илгээнэ үү — нэг ажлын өдөрт үнэ.',
    'cta.title': 'Үйлдвэрийн шууд үнийн саналаа аваарай',
    'cta.p': 'Төслийн мэдээллээ илгээнэ үү — экспортын баг 24 цагийн дотор үнэ, хугацаа, хүргэлтийн сонголттой хариулах болно.',
}
