# -*- coding: utf-8 -*-
"""Page data: quality.html — Quality & Certification (质量体系与认证), 11 languages."""

CFG = {
    'file': 'quality.html',
    'cta2_href': 'https://ouzcable.com/technical.html',
    'title': 'Cable Quality & Certification | ISO 9001 IEC 60502-2 GOST 31996 Tested Factory — OUZHI Cable 欧智电缆 | 电缆质量体系与认证',
    'desc': 'Quality system of OUZHI Cable (欧智电缆) source factory: ISO 9001 management, raw-material traceability, in-line process control, 100% routine testing per IEC 60502-2, GOST 31996 and GB/T 12706. Type test reports, third-party inspection and EAC/CE documentation available. Contact: info@ouzcable.com | +998 99 851 6999.',
    'keywords': 'cable quality certification, IEC 60502-2 type test, GOST 31996 certificate, ISO 9001 cable factory, cable routine test, partial discharge test cable, third-party inspection cable, EAC certificate cable, CE cable Europe, cable factory quality system, OUZHI Cable, 欧智电缆, 电缆质量认证, 出厂检测, medium voltage cable testing',
    'ld_headline': 'Cable Quality, Testing & Certification — OUZHI Cable Source Factory',
    'ld_desc': 'ISO 9001 quality management, raw-material traceability and 100% routine testing per IEC 60502-2 / GOST 31996 / GB/T 12706 at OUZHI Cable source factory. Contact info@ouzcable.com | +998 99 851 6999.',
    'sections': [
        {'type': 'hero'},
        {'type': 'cards', 'title': 's1.title', 'p': 's1.p', 'c': 's1.c'},
        {'type': 'table', 'title': 's2.title', 'p': 's2.p', 'th': 's2.th', 'cols': 4, 'rows': [
            ['s2.r1c1', 's2.r1c2', 's2.r1c3', 's2.r1c4'],
            ['s2.r2c1', 's2.r2c2', 's2.r2c3', 's2.r2c4'],
            ['s2.r3c1', 's2.r3c2', 's2.r3c3', 's2.r3c4'],
            ['s2.r4c1', 's2.r4c2', 's2.r4c3', 's2.r4c4'],
            ['s2.r5c1', 's2.r5c2', 's2.r5c3', 's2.r5c4'],
            ['s2.r6c1', 's2.r6c2', 's2.r6c3', 's2.r6c4'],
        ]},
        {'type': 'steps', 'title': 's3.title', 'p': 's3.p', 's': 's3.s', 'n': 5},
        {'type': 'highlight', 'title': 's4.title', 'p': 's4.p'},
        {'type': 'faq', 'title': 'faq.title', 'n': 5},
        {'type': 'cta'}
    ],
}

I18N = {}

I18N['en'] = {
    'hero.eyebrow': 'Quality System · Testing · Certifications',
    'hero.title': 'Certified Quality, <span class="accent">Tested on Every Drum</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — ISO 9001 Quality System · IEC / GOST / GB Standards',
    'hero.lead': 'Quality is not a promise but a process: ISO 9001 quality management, raw-material traceability, in-line process control and 100% routine testing on every drum before shipment.',
    'hero.cta1': 'Request Test Reports', 'hero.cta2': 'View Technical Specs',
    's1.title': 'Our Quality System at a Glance',
    's1.p': 'From incoming raw material to the tested drum, every stage is controlled, documented and verifiable.',
    's1.c1t': 'ISO 9001 Management System', 's1.c1d': 'Certified quality management covering procurement, production and inspection.',
    's1.c2t': 'Raw Material Traceability', 's1.c2d': 'Copper, aluminium, XLPE compound and sheathing materials are batch-tracked from receipt to finished drum.',
    's1.c3t': 'In-Line Process Control', 's1.c3d': 'Continuous monitoring of conductor, insulation eccentricity, screen and sheath during production.',
    's1.c4t': '100% Routine Testing', 's1.c4d': 'Every drum undergoes routine testing per IEC 60502-2 before it is released for shipment.',
    's2.title': 'Standards & Certification Matrix',
    's2.p': 'We manufacture to the standards your market requires — and provide the certificates to prove it.',
    's2.th1': 'Standard', 's2.th2': 'Scope', 's2.th3': 'Typical Markets', 's2.th4': 'Key Tests',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': 'MV cables 6–36 kV', 's2.r1c3': 'Global', 's2.r1c4': 'Type & routine tests, partial discharge',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'MV power cables', 's2.r2c3': 'Russia, CIS, Central Asia', 's2.r2c4': 'EAC certification, cold resistance',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'MV cables', 's2.r3c3': 'China', 's2.r3c4': 'Type tests per national standard',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'Quality management system', 's2.r4c3': 'Global', 's2.r4c4': 'Audited management system',
    's2.r5c1': 'CE', 's2.r5c2': 'EU conformity', 's2.r5c3': 'Europe', 's2.r5c4': 'Low voltage & RoHS directives',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'Flame retardance', 's2.r6c3': 'Global', 's2.r6c4': 'Vertical flame propagation test',
    's3.title': 'From Raw Material to Tested Drum',
    's3.p': 'A controlled journey through five quality checkpoints.',
    's3.s1t': 'Raw Material Inspection', 's3.s1d': 'Incoming copper, aluminium and compounds verified against specifications.',
    's3.s2t': 'Conductor Testing', 's3.s2d': 'Cross-section, DC resistance and stranding verified.',
    's3.s3t': 'Insulation & Screening Checks', 's3.s3d': 'Eccentricity, thickness and screen continuity monitored in-line.',
    's3.s4t': 'Partial Discharge & HV Tests', 's3.s4d': 'Type-tested performance and routine high-voltage withstand on each drum.',
    's3.s5t': 'Release & Certificate', 's3.s5d': 'Approved drums receive certificates and are packed for export.',
    's4.title': 'Verification You Can Trust',
    's4.p': 'Independent verification is welcome at every stage: third-party inspection, witnessed type tests and on-site sampling are all available. Serious buyers may also arrange a factory audit before placing an order.',
    'faq.title': 'FAQ — Quality & Certification',
    'faq.q1': 'Can you provide type test reports?', 'faq.a1': 'Yes — IEC/GOST/GB type test reports from our accredited laboratory are available on request.',
    'faq.q2': 'Do you allow third-party inspection?', 'faq.a2': 'Absolutely — SGS, TÜV, BV or your nominated inspector is welcome during production and before shipment.',
    'faq.q3': 'What is the warranty period?', 'faq.a3': 'We provide a 12-month warranty against manufacturing defects; extended terms can be agreed per contract.',
    'faq.q4': 'Do you offer certificates for EAC markets?', 'faq.a4': 'Yes — EAC declaration/certification documentation for Russia, CIS and Central Asia is prepared with every shipment.',
    'faq.q5': 'How do I verify quality before ordering?', 'faq.a5': 'Request samples, test reports and a factory audit — we welcome serious buyers at our plant.',
    'cta.title': 'Request Certificates & Test Reports',
    'cta.p': 'Tell us which standard or certification your project requires — we will provide the relevant documents and answer any quality questions within 24 hours.',
}

I18N['zh'] = {
    'hero.eyebrow': '质量体系 · 检测 · 认证',
    'hero.title': '认证质量，<span class="accent">每盘必检</span>',
    'hero.sub': '欧智电缆（OUZHI Cable）— ISO 9001 质量体系 · IEC / GOST / GB 标准',
    'hero.lead': '质量不是承诺而是流程：ISO 9001 质量管理、原材料追溯、在线过程控制，以及每盘电缆出厂前 100% 常规检测。',
    'hero.cta1': '索取检测报告', 'hero.cta2': '查看技术参数',
    's1.title': '质量体系一览',
    's1.p': '从进料原材料到检测合格出厂，每一环节都受控、可记录、可验证。',
    's1.c1t': 'ISO 9001 管理体系', 's1.c1d': '覆盖采购、生产与检验的认证质量管理体系。',
    's1.c2t': '原材料可追溯', 's1.c2d': '铜、铝、XLPE 料与护套料从进厂到成品盘全程批次跟踪。',
    's1.c3t': '在线过程控制', 's1.c3d': '生产中持续监控导体、绝缘偏心、屏蔽与护套。',
    's1.c4t': '100% 出厂常规检测', 's1.c4d': '每盘电缆按 IEC 60502-2 完成常规检测后方可放行发运。',
    's2.title': '标准与认证矩阵',
    's2.p': '我们按您市场要求的标准生产——并提供证明文件。',
    's2.th1': '标准', 's2.th2': '范围', 's2.th3': '主要市场', 's2.th4': '关键检测',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': '6–36kV 中压电缆', 's2.r1c3': '全球', 's2.r1c4': '型式与常规试验、局放',
    's2.r2c1': 'GOST 31996', 's2.r2c2': '中压电力电缆', 's2.r2c3': '俄罗斯、独联体、中亚', 's2.r2c4': 'EAC 认证、耐寒性',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': '中压电缆', 's2.r3c3': '中国', 's2.r3c4': '国家标准型式试验',
    's2.r4c1': 'ISO 9001', 's2.r4c2': '质量管理体系', 's2.r4c3': '全球', 's2.r4c4': '审核管理体系',
    's2.r5c1': 'CE', 's2.r5c2': '欧盟符合性', 's2.r5c3': '欧洲', 's2.r5c4': '低电压与 RoHS 指令',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': '阻燃性能', 's2.r6c3': '全球', 's2.r6c4': '垂直燃烧试验',
    's3.title': '从原材料到检测合格出厂',
    's3.p': '五道质量关卡的受控旅程。',
    's3.s1t': '原材料检验', 's3.s1d': '进厂铜、铝与材料按规格验证。',
    's3.s2t': '导体检测', 's3.s2d': '验证截面、直流电阻与绞合。',
    's3.s3t': '绝缘与屏蔽检查', 's3.s3d': '在线监控偏心、厚度与屏蔽连续性。',
    's3.s4t': '局放与高压试验', 's3.s4d': '型式试验性能与每盘常规耐压。',
    's3.s5t': '放行与证书', 's3.s5d': '合格盘出具证书并包装出口。',
    's4.title': '可信的第三方验证',
    's4.p': '每个环节都欢迎独立验证：第三方检验、见证型式试验与现场抽样均可安排。重要买家还可在下单前安排工厂审核。',
    'faq.title': '常见问题 — 质量与认证',
    'faq.q1': '能否提供型式试验报告？', 'faq.a1': '可以。认证实验室出具的 IEC/GOST/GB 型式试验报告可按需提供。',
    'faq.q2': '是否允许第三方检验？', 'faq.a2': '完全可以。欢迎 SGS、TÜV、BV 或您指定的检验机构在生产期间与发货前验货。',
    'faq.q3': '质保期多长？', 'faq.a3': '提供 12 个月制造缺陷质保；更长条款可按合同约定。',
    'faq.q4': '是否提供 EAC 市场证书？', 'faq.a4': '提供。面向俄罗斯、独联体与中亚的 EAC 声明/认证文件随每批货物备齐。',
    'faq.q5': '下单前如何验证质量？', 'faq.a5': '索取样品、检测报告并安排工厂审核——我们欢迎认真买家到厂考察。',
    'cta.title': '索取证书与检测报告',
    'cta.p': '告知您的项目需要哪种标准或认证——我们将在 24 小时内提供相关文件并解答质量问题。',
}

I18N['ru'] = {
    'hero.eyebrow': 'Система качества · Испытания · Сертификация',
    'hero.title': 'Сертифицированное качество, <span class="accent">проверено на каждом барабане</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — система качества ISO 9001 · стандарты IEC / GOST / GB',
    'hero.lead': 'Качество — это не обещание, а процесс: менеджмент качества ISO 9001, прослеживаемость сырья, контроль в процессе производства и 100% контроль каждого барабана перед отгрузкой.',
    'hero.cta1': 'Запросить протоколы', 'hero.cta2': 'Технические параметры',
    's1.title': 'Наша система качества',
    's1.p': 'От поступающего сырья до протестированного барабана — каждый этап контролируется, документируется и проверяем.',
    's1.c1t': 'Система менеджмента ISO 9001', 's1.c1d': 'Сертифицированный менеджмент качества, охватывающий закупки, производство и контроль.',
    's1.c2t': 'Прослеживаемость сырья', 's1.c2d': 'Медь, алюминий, XLPE-компаунд и оболочки отслеживаются по партиям от приёмки до готового барабана.',
    's1.c3t': 'Контроль в процессе производства', 's1.c3d': 'Непрерывный мониторинг жилы, эксцентриситета изоляции, экрана и оболочки.',
    's1.c4t': '100% контроль каждой партии', 's1.c4d': 'Каждый барабан проходит контроль по IEC 60502-2 перед отгрузкой.',
    's2.title': 'Матрица стандартов и сертификатов',
    's2.p': 'Мы производим по стандартам вашего рынка — и предоставляем сертификаты, подтверждающие это.',
    's2.th1': 'Стандарт', 's2.th2': 'Область', 's2.th3': 'Основные рынки', 's2.th4': 'Ключевые испытания',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': 'Кабели СН 6–36 кВ', 's2.r1c3': 'Мир', 's2.r1c4': 'Типовые и контрольные, частичные разряды',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'Силовые кабели СН', 's2.r2c3': 'Россия, СНГ, Центральная Азия', 's2.r2c4': 'Сертификация EAC, холодостойкость',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'Кабели СН', 's2.r3c3': 'Китай', 's2.r3c4': 'Типовые испытания по нацстандарту',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'Система менеджмента качества', 's2.r4c3': 'Мир', 's2.r4c4': 'Аудит системы менеджмента',
    's2.r5c1': 'CE', 's2.r5c2': 'Соответствие ЕС', 's2.r5c3': 'Европа', 's2.r5c4': 'Директивы по низкому напряжению и RoHS',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'Огнестойкость', 's2.r6c3': 'Мир', 's2.r6c4': 'Испытание на вертикальное распространение',
    's3.title': 'От сырья до проверенного барабана',
    's3.p': 'Контролируемый путь через пять контрольных точек.',
    's3.s1t': 'Входной контроль сырья', 's3.s1d': 'Медь, алюминий и компаунды проверяются на соответствие спецификациям.',
    's3.s2t': 'Испытание жилы', 's3.s2d': 'Проверка сечения, омического сопротивления и скрутки.',
    's3.s3t': 'Контроль изоляции и экрана', 's3.s3d': 'Эксцентриситет, толщина и непрерывность экрана контролируются в линии.',
    's3.s4t': 'Частичные разряды и высокое напряжение', 's3.s4d': 'Типовые характеристики и контрольное высокое напряжение на каждом барабане.',
    's3.s5t': 'Разрешение и сертификат', 's3.s5d': 'Проверенные барабаны получают сертификаты и упаковываются на экспорт.',
    's4.title': 'Проверка, которой можно доверять',
    's4.p': 'Независимая проверка приветствуется на каждом этапе: инспекция третьей стороной, присутствие на типовых испытаниях и отбор проб на площадке. Серьёзные покупатели могут также провести аудит завода перед заказом.',
    'faq.title': 'FAQ — качество и сертификация',
    'faq.q1': 'Предоставляете ли протоколы типовых испытаний?', 'faq.a1': 'Да — протоколы типовых испытаний IEC/GOST/GB из аккредитованной лаборатории по запросу.',
    'faq.q2': 'Разрешаете ли инспекцию третьей стороной?', 'faq.a2': 'Безусловно — SGS, TÜV, BV или ваш инспектор приветствуются во время производства и перед отгрузкой.',
    'faq.q3': 'Каков гарантийный срок?', 'faq.a3': 'Предоставляем гарантию 12 месяцев на производственные дефекты; расширенные условия — по контракту.',
    'faq.q4': 'Предоставляете ли сертификаты для рынков EAC?', 'faq.a4': 'Да — документация EAC для России, СНГ и Центральной Азии готовится к каждой отгрузке.',
    'faq.q5': 'Как проверить качество до заказа?', 'faq.a5': 'Запросите образцы, протоколы испытаний и аудит завода — мы ждём серьёзных покупателей на производстве.',
    'cta.title': 'Запросите сертификаты и протоколы',
    'cta.p': 'Укажите, какой стандарт или сертификат нужен вашему проекту — предоставим документы и ответим на вопросы по качеству в течение 24 часов.',
}

I18N['ar'] = {
    'hero.eyebrow': 'نظام الجودة · الاختبارات · الشهادات',
    'hero.title': 'جودة معتمدة، <span class="accent">مختبرة على كل بكرة</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — نظام جودة ISO 9001 · معايير IEC / GOST / GB',
    'hero.lead': 'الجودة ليست وعداً بل عملية: إدارة جودة ISO 9001، تتبع المواد الخام، مراقبة العملية خطياً، واختبار 100% لكل بكرة قبل الشحن.',
    'hero.cta1': 'طلب تقارير الاختبار', 'hero.cta2': 'عرض المواصفات الفنية',
    's1.title': 'نظام الجودة في لمحة',
    's1.p': 'من المواد الخام الواردة إلى البكرة المختبرة، كل مرحلة خاضعة للرقابة والتوثيق والتحقق.',
    's1.c1t': 'نظام إدارة ISO 9001', 's1.c1d': 'إدارة جودة معتمدة تغطي الشراء والإنتاج والفحص.',
    's1.c2t': 'تتبع المواد الخام', 's1.c2d': 'النحاس والألمنيوم ومركبات XLPE والمواد العازلة تُتتبع بالدفعات من الاستلام إلى البكرة النهائية.',
    's1.c3t': 'مراقبة العملية خطياً', 's1.c3d': 'مراقبة مستمرة للموصل وتمركز العزل والدرع والغلاف أثناء الإنتاج.',
    's1.c4t': 'اختبار روتيني 100%', 's1.c4d': 'كل بكرة تخضع للاختبار الروتيني وفق IEC 60502-2 قبل الإفراج للشحن.',
    's2.title': 'مصفوفة المعايير والشهادات',
    's2.p': 'ننتج وفق المعايير التي يتطلبها سوقك — ونقدم الشهادات التي تثبت ذلك.',
    's2.th1': 'المعيار', 's2.th2': 'النطاق', 's2.th3': 'الأسواق الرئيسية', 's2.th4': 'الاختبارات الرئيسية',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': 'كابلات الجهد المتوسط 6–36 ك.ف', 's2.r1c3': 'عالمي', 's2.r1c4': 'اختبارات النوع والروتين، التفريغ الجزئي',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'كابلات الجهد المتوسط', 's2.r2c3': 'روسيا، رابطة الدول، آسيا الوسطى', 's2.r2c4': 'شهادة EAC، مقاومة البرد',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'كابلات الجهد المتوسط', 's2.r3c3': 'الصين', 's2.r3c4': 'اختبارات النوع وفق المعيار الوطني',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'نظام إدارة الجودة', 's2.r4c3': 'عالمي', 's2.r4c4': 'نظام إدارة مُدقق',
    's2.r5c1': 'CE', 's2.r5c2': 'مطابقة الاتحاد الأوروبي', 's2.r5c3': 'أوروبا', 's2.r5c4': 'توجيهات الجهد المنخفض وRoHS',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'مقاومة اللهب', 's2.r6c3': 'عالمي', 's2.r6c4': 'اختبار انتشار اللهب الرأسي',
    's3.title': 'من المواد الخام إلى البكرة المختبرة',
    's3.p': 'رحلة خاضعة للرقابة عبر خمس نقاط جودة.',
    's3.s1t': 'فحص المواد الخام', 's3.s1d': 'التحقق من النحاس والألمنيوم والمركبات الواردة مقابل المواصفات.',
    's3.s2t': 'اختبار الموصل', 's3.s2d': 'التحقق من المقطع والمقاومة والجدل.',
    's3.s3t': 'فحوصات العزل والدرع', 's3.s3d': 'مراقبة التمركز والسمك واستمرارية الدرع خطياً.',
    's3.s4t': 'التفريغ الجزئي واختبارات الجهد العالي', 's3.s4d': 'أداء النوع واختبار الجهد الروتيني على كل بكرة.',
    's3.s5t': 'الإفراج والشهادة', 's3.s5d': 'البكرات المعتمدة تحصل على شهادات وتُعبأ للتصدير.',
    's4.title': 'تحقق يمكنك الوثوق به',
    's4.p': 'التحقق المستقل مرحب به في كل مرحلة: فحص طرف ثالث، حضور اختبارات النوع، وأخذ عينات في الموقع. كما يمكن للمشترين الجادين ترتيب تدقيق للمصنع قبل الطلب.',
    'faq.title': 'الأسئلة الشائعة — الجودة والشهادات',
    'faq.q1': 'هل توفرون تقارير اختبارات النوع؟', 'faq.a1': 'نعم — تقارير IEC/GOST/GB من مختبرنا المعتمد متاحة عند الطلب.',
    'faq.q2': 'هل تسمحون بفحص طرف ثالث؟', 'faq.a2': 'بالتأكيد — SGS أو TÜV أو BV أو المفتش الذي تختاره مرحب به أثناء الإنتاج وقبل الشحن.',
    'faq.q3': 'ما مدة الضمان؟', 'faq.a3': 'نقدم ضمان 12 شهراً ضد عيوب التصنيع؛ ويمكن الاتفاق على شروط أطول بالعقد.',
    'faq.q4': 'هل تقدمون شهادات لأسواق EAC؟', 'faq.a4': 'نعم — وثائق إعلان/شهادة EAC لروسيا ورابطة الدول وآسيا الوسطى تُجهز مع كل شحنة.',
    'faq.q5': 'كيف أتحقق من الجودة قبل الطلب؟', 'faq.a5': 'اطلب عينات وتقارير اختبار ودعوة لتدقيق المصنع — نرحب بالمشترين الجادين في منشأتنا.',
    'cta.title': 'اطلب الشهادات وتقارير الاختبار',
    'cta.p': 'أخبرنا بالمعيار أو الشهادة التي يتطلبها مشروعك — سنوفر الوثائق ذات الصلة ونجيب على أسئلة الجودة خلال 24 ساعة.',
}

I18N['fr'] = {
    'hero.eyebrow': 'Système qualité · Essais · Certifications',
    'hero.title': 'Qualité certifiée, <span class="accent">essayée sur chaque touret</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — système qualité ISO 9001 · normes IEC / GOST / GB',
    'hero.lead': 'La qualité n\u2019est pas une promesse mais un processus : management ISO 9001, traçabilité des matières premières, contrôle en ligne et 100% d\u2019essais courants sur chaque touret avant expédition.',
    'hero.cta1': 'Demander les rapports', 'hero.cta2': 'Voir les spécifications',
    's1.title': 'Notre système qualité en un coup d\u2019œil',
    's1.p': 'De la matière première au touret essayé, chaque étape est contrôlée, documentée et vérifiable.',
    's1.c1t': 'Système de management ISO 9001', 's1.c1d': 'Management qualité certifié couvrant achats, production et contrôle.',
    's1.c2t': 'Traçabilité des matières premières', 's1.c2d': 'Cuivre, aluminium, compound XLPE et gaines suivis par lot, de la réception au touret fini.',
    's1.c3t': 'Contrôle en ligne', 's1.c3d': 'Surveillance continue du conducteur, de l\u2019excentricité d\u2019isolation, de l\u2019écran et de la gaine.',
    's1.c4t': '100% d\u2019essais courants', 's1.c4d': 'Chaque touret subit les essais courants selon IEC 60502-2 avant expédition.',
    's2.title': 'Matrice normes & certifications',
    's2.p': 'Nous fabriquons selon les normes de votre marché — et fournissons les certificats qui le prouvent.',
    's2.th1': 'Norme', 's2.th2': 'Domaine', 's2.th3': 'Marchés types', 's2.th4': 'Essais clés',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': 'Câbles MT 6–36 kV', 's2.r1c3': 'Mondial', 's2.r1c4': 'Essais de type et courants, décharges partielles',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'Câbles MT', 's2.r2c3': 'Russie, CEI, Asie centrale', 's2.r2c4': 'Certification EAC, résistance au froid',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'Câbles MT', 's2.r3c3': 'Chine', 's2.r3c4': 'Essais de type selon norme nationale',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'Système de management qualité', 's2.r4c3': 'Mondial', 's2.r4c4': 'Système audité',
    's2.r5c1': 'CE', 's2.r5c2': 'Conformité UE', 's2.r5c3': 'Europe', 's2.r5c4': 'Directives basse tension & RoHS',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'Résistance à la flamme', 's2.r6c3': 'Mondial', 's2.r6c4': 'Essai de propagation verticale',
    's3.title': 'De la matière première au touret essayé',
    's3.p': 'Un parcours contrôlé à travers cinq points de contrôle qualité.',
    's3.s1t': 'Inspection des matières premières', 's3.s1d': 'Cuivre, aluminium et compounds vérifiés contre les spécifications.',
    's3.s2t': 'Essai du conducteur', 's3.s2d': 'Section, résistance DC et câblage vérifiés.',
    's3.s3t': 'Contrôles isolation & écran', 's3.s3d': 'Excentricité, épaisseur et continuité d\u2019écran surveillées en ligne.',
    's3.s4t': 'Décharges partielles & HT', 's3.s4d': 'Performance de type et tenue haute tension courante sur chaque touret.',
    's3.s5t': 'Libération & certificat', 's3.s5d': 'Les tourets approuvés reçoivent certificats et sont emballés pour l\u2019export.',
    's4.title': 'Une vérification en laquelle vous pouvez croire',
    's4.p': 'La vérification indépendante est la bienvenue à chaque étape : inspection tierce, essais de type témoins et échantillonnage sur site. Les acheteurs sérieux peuvent aussi auditer l\u2019usine avant de commander.',
    'faq.title': 'FAQ — qualité & certification',
    'faq.q1': 'Fournissez-vous des rapports d\u2019essais de type ?', 'faq.a1': 'Oui — rapports IEC/GOST/GB de notre laboratoire accrédité sur demande.',
    'faq.q2': 'Autorisez-vous l\u2019inspection par un tiers ?', 'faq.a2': 'Absolument — SGS, TÜV, BV ou votre inspecteur désigné est bienvenu en production et avant expédition.',
    'faq.q3': 'Quelle est la période de garantie ?', 'faq.a3': 'Garantie 12 mois contre défauts de fabrication ; conditions étendues possibles par contrat.',
    'faq.q4': 'Proposez-vous des certificats pour les marchés EAC ?', 'faq.a4': 'Oui — documentation EAC pour la Russie, la CEI et l\u2019Asie centrale préparée à chaque expédition.',
    'faq.q5': 'Comment vérifier la qualité avant de commander ?', 'faq.a5': 'Demandez échantillons, rapports d\u2019essais et audit d\u2019usine — nous accueillons les acheteurs sérieux.',
    'cta.title': 'Demandez certificats & rapports d\u2019essais',
    'cta.p': 'Indiquez la norme ou certification requise pour votre projet — documents fournis et questions qualité répondues sous 24 h.',
}

I18N['de'] = {
    'hero.eyebrow': 'Qualitätssystem · Prüfungen · Zertifizierungen',
    'hero.title': 'Zertifizierte Qualität, <span class="accent">an jeder Trommel geprüft</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — ISO-9001-Qualitätssystem · IEC / GOST / GB-Normen',
    'hero.lead': 'Qualität ist kein Versprechen, sondern ein Prozess: ISO-9001-Qualitätsmanagement, Rohstoff-Rückverfolgbarkeit, Inline-Prozesskontrolle und 100% Routineprüfung jeder Trommel vor Versand.',
    'hero.cta1': 'Prüfberichte anfordern', 'hero.cta2': 'Technische Daten',
    's1.title': 'Unser Qualitätssystem im Überblick',
    's1.p': 'Vom Rohstoff bis zur geprüften Trommel — jede Stufe wird kontrolliert, dokumentiert und ist verifizierbar.',
    's1.c1t': 'ISO-9001-Managementsystem', 's1.c1d': 'Zertifiziertes Qualitätsmanagement für Beschaffung, Produktion und Prüfung.',
    's1.c2t': 'Rohstoff-Rückverfolgbarkeit', 's1.c2d': 'Kupfer, Aluminium, XLPE-Compound und Mantelmaterialien werden chargenweise vom Wareneingang bis zur fertigen Trommel verfolgt.',
    's1.c3t': 'Inline-Prozesskontrolle', 's1.c3d': 'Kontinuierliche Überwachung von Leiter, Isolations-Exzentrizität, Schirm und Mantel.',
    's1.c4t': '100% Routineprüfung', 's1.c4d': 'Jede Trommel durchläuft die Routineprüfung nach IEC 60502-2 vor Freigabe.',
    's2.title': 'Normen- und Zertifizierungsmatrix',
    's2.p': 'Wir fertigen nach den Normen Ihres Marktes — und liefern die Zertifikate zum Beweis.',
    's2.th1': 'Norm', 's2.th2': 'Geltungsbereich', 's2.th3': 'Typische Märkte', 's2.th4': 'Wichtige Prüfungen',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': 'MS-Kabel 6–36 kV', 's2.r1c3': 'Weltweit', 's2.r1c4': 'Typprüfung, Routine, Teilentladung',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'MS-Energiekabel', 's2.r2c3': 'Russland, GUS, Zentralasien', 's2.r2c4': 'EAC-Zertifizierung, Kältebeständigkeit',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'MS-Kabel', 's2.r3c3': 'China', 's2.r3c4': 'Typprüfung nach nationaler Norm',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'Qualitätsmanagementsystem', 's2.r4c3': 'Weltweit', 's2.r4c4': 'Auditiertes Managementsystem',
    's2.r5c1': 'CE', 's2.r5c2': 'EU-Konformität', 's2.r5c3': 'Europa', 's2.r5c4': 'Niederspannungs- & RoHS-Richtlinien',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'Flammwidrigkeit', 's2.r6c3': 'Weltweit', 's2.r6c4': 'Vertikale Flammenausbreitung',
    's3.title': 'Vom Rohstoff zur geprüften Trommel',
    's3.p': 'Ein kontrollierter Weg durch fünf Qualitätskontrollpunkte.',
    's3.s1t': 'Rohstoffprüfung', 's3.s1d': 'Eingehendes Kupfer, Aluminium und Compounds gegen Spezifikationen geprüft.',
    's3.s2t': 'Leiterprüfung', 's3.s2d': 'Querschnitt, Gleichstromwiderstand und Verseilung geprüft.',
    's3.s3t': 'Isolations- & Schirmprüfung', 's3.s3d': 'Exzentrizität, Dicke und Schirmdurchgang inline überwacht.',
    's3.s4t': 'Teilentladung & HV-Prüfungen', 's3.s4d': 'Typgeprüfte Leistung und Routine-Hochspannung an jeder Trommel.',
    's3.s5t': 'Freigabe & Zertifikat', 's3.s5d': 'Freigegebene Trommeln erhalten Zertifikate und werden exportverpackt.',
    's4.title': 'Verifizierung, der Sie vertrauen können',
    's4.p': 'Unabhängige Verifizierung ist auf jeder Stufe willkommen: Drittprüfung, beaufsichtigte Typprüfungen und Probenahme vor Ort. Ernsthafte Käufer können vor der Bestellung auch ein Werksaudit vereinbaren.',
    'faq.title': 'FAQ — Qualität & Zertifizierung',
    'faq.q1': 'Liefern Sie Typprüfberichte?', 'faq.a1': 'Ja — IEC-/GOST-/GB-Typprüfberichte aus unserem akkreditierten Labor auf Anfrage.',
    'faq.q2': 'Erlauben Sie Drittprüfungen?', 'faq.a2': 'Absolut — SGS, TÜV, BV oder Ihr benannter Prüfer ist während Produktion und vor Versand willkommen.',
    'faq.q3': 'Wie lang ist die Garantiezeit?', 'faq.a3': '12 Monate Garantie auf Herstellungsfehler; verlängerte Bedingungen nach Vertrag möglich.',
    'faq.q4': 'Bieten Sie Zertifikate für EAC-Märkte?', 'faq.a4': 'Ja — EAC-Dokumentation für Russland, GUS und Zentralasien wird mit jeder Lieferung vorbereitet.',
    'faq.q5': 'Wie prüfe ich Qualität vor der Bestellung?', 'faq.a5': 'Fordern Sie Muster, Prüfberichte und ein Werksaudit an — wir begrüßen ernsthafte Käufer im Werk.',
    'cta.title': 'Zertifikate & Prüfberichte anfordern',
    'cta.p': 'Nennen Sie die geforderte Norm oder Zertifizierung — wir liefern die Dokumente und beantworten Qualitätsfragen innerhalb von 24 Stunden.',
}

I18N['uk'] = {
    'hero.eyebrow': 'Система якості · Випробування · Сертифікація',
    'hero.title': 'Сертифікована якість, <span class="accent">перевірено на кожному барабані</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — система якості ISO 9001 · стандарти IEC / GOST / GB',
    'hero.lead': 'Якість — це не обіцянка, а процес: менеджмент якості ISO 9001, простежуваність сировини, контроль у процесі виробництва та 100% контроль кожного барабана перед відвантаженням.',
    'hero.cta1': 'Запросити протоколи', 'hero.cta2': 'Технічні параметри',
    's1.title': 'Наша система якості',
    's1.p': 'Від сировини до протестованого барабана — кожен етап контролюється, документується та перевіряється.',
    's1.c1t': 'Система менеджменту ISO 9001', 's1.c1d': 'Сертифікований менеджмент якості: закупівлі, виробництво, контроль.',
    's1.c2t': 'Простежуваність сировини', 's1.c2d': 'Мідь, алюміній, XLPE-компаунд та оболонки відстежуються за партіями від приймання до готового барабана.',
    's1.c3t': 'Контроль у процесі виробництва', 's1.c3d': 'Безперервний моніторинг жили, ексцентриситету ізоляції, екрана та оболонки.',
    's1.c4t': '100% контроль кожної партії', 's1.c4d': 'Кожен барабан проходить контроль за IEC 60502-2 перед відвантаженням.',
    's2.title': 'Матриця стандартів і сертифікатів',
    's2.p': 'Виробляємо за стандартами вашого ринку — і надаємо сертифікати, що це підтверджують.',
    's2.th1': 'Стандарт', 's2.th2': 'Сфера', 's2.th3': 'Основні ринки', 's2.th4': 'Ключові випробування',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': 'Кабелі СН 6–36 кВ', 's2.r1c3': 'Світ', 's2.r1c4': 'Типові та контрольні, часткові розряди',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'Силові кабелі СН', 's2.r2c3': 'Росія, СНД, Центральна Азія', 's2.r2c4': 'Сертифікація EAC, холодостійкість',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'Кабелі СН', 's2.r3c3': 'Китай', 's2.r3c4': 'Типові випробування за нацстандартом',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'Система менеджменту якості', 's2.r4c3': 'Світ', 's2.r4c4': 'Аудит системи менеджменту',
    's2.r5c1': 'CE', 's2.r5c2': 'Відповідність ЄС', 's2.r5c3': 'Європа', 's2.r5c4': 'Директиви з низької напруги та RoHS',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'Вогнестійкість', 's2.r6c3': 'Світ', 's2.r6c4': 'Випробування на вертикальне поширення полум\u2019я',
    's3.title': 'Від сировини до перевіреного барабана',
    's3.p': 'Контрольований шлях через п\u2019ять контрольних точок якості.',
    's3.s1t': 'Вхідний контроль сировини', 's3.s1d': 'Мідь, алюміній і компаунди перевіряються на відповідність специфікаціям.',
    's3.s2t': 'Випробування жили', 's3.s2d': 'Перевірка перерізу, омічного опору та скрутки.',
    's3.s3t': 'Контроль ізоляції та екрана', 's3.s3d': 'Ексцентриситет, товщина та безперервність екрана контролюються в лінії.',
    's3.s4t': 'Часткові розряди та висока напруга', 's3.s4d': 'Типові характеристики та контрольна висока напруга на кожному барабані.',
    's3.s5t': 'Дозвіл і сертифікат', 's3.s5d': 'Перевірені барабани отримують сертифікати та пакуються на експорт.',
    's4.title': 'Перевірка, якій можна довіряти',
    's4.p': 'Незалежна перевірка вітається на кожному етапі: інспекція третьою стороною, присутність на типових випробуваннях та відбір проб на майданчику. Серйозні покупці можуть також провести аудит заводу перед замовленням.',
    'faq.title': 'Питання та відповіді — якість і сертифікація',
    'faq.q1': 'Чи надаєте протоколи типових випробувань?', 'faq.a1': 'Так — протоколи IEC/GOST/GB з акредитованої лабораторії за запитом.',
    'faq.q2': 'Чи дозволяєте інспекцію третьою стороною?', 'faq.a2': 'Безумовно — SGS, TÜV, BV або ваш інспектор вітається під час виробництва та перед відвантаженням.',
    'faq.q3': 'Який гарантійний термін?', 'faq.a3': 'Гарантія 12 місяців на виробничі дефекти; розширені умови — за контрактом.',
    'faq.q4': 'Чи надаєте сертифікати для ринків EAC?', 'faq.a4': 'Так — документація EAC для Росії, СНД і Центральної Азії готується до кожної відгрузки.',
    'faq.q5': 'Як перевірити якість перед замовленням?', 'faq.a5': 'Запросіть зразки, протоколи випробувань та аудит заводу — чекаємо серйозних покупців на виробництві.',
    'cta.title': 'Запросіть сертифікати та протоколи',
    'cta.p': 'Вкажіть, який стандарт чи сертифікат потрібен вашому проєкту — надамо документи та відповімо на питання щодо якості протягом 24 годин.',
}

I18N['es'] = {
    'hero.eyebrow': 'Sistema de calidad · Ensayos · Certificaciones',
    'hero.title': 'Calidad certificada, <span class="accent">ensayada en cada bobina</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — sistema de calidad ISO 9001 · normas IEC / GOST / GB',
    'hero.lead': 'La calidad no es una promesa sino un proceso: gestión ISO 9001, trazabilidad de materias primas, control en línea y 100% de ensayos rutinarios en cada bobina antes del envío.',
    'hero.cta1': 'Solicitar informes de ensayo', 'hero.cta2': 'Ver especificaciones',
    's1.title': 'Nuestro sistema de calidad de un vistazo',
    's1.p': 'De la materia prima a la bobina ensayada, cada etapa está controlada, documentada y verificable.',
    's1.c1t': 'Sistema de gestión ISO 9001', 's1.c1d': 'Gestión de calidad certificada que cubre compras, producción e inspección.',
    's1.c2t': 'Trazabilidad de materias primas', 's1.c2d': 'Cobre, aluminio, compound XLPE y cubiertas rastreados por lote, de la recepción a la bobina final.',
    's1.c3t': 'Control de proceso en línea', 's1.c3d': 'Monitoreo continuo del conductor, excentricidad de aislamiento, pantalla y cubierta.',
    's1.c4t': '100% ensayos rutinarios', 's1.c4d': 'Cada bobina pasa ensayos rutinarios según IEC 60502-2 antes de su liberación.',
    's2.title': 'Matriz de normas y certificaciones',
    's2.p': 'Fabricamos según las normas que su mercado requiere — y entregamos los certificados que lo prueban.',
    's2.th1': 'Norma', 's2.th2': 'Alcance', 's2.th3': 'Mercados típicos', 's2.th4': 'Ensayos clave',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': 'Cables MT 6–36 kV', 's2.r1c3': 'Global', 's2.r1c4': 'Ensayos de tipo y rutina, descargas parciales',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'Cables MT', 's2.r2c3': 'Rusia, CEI, Asia Central', 's2.r2c4': 'Certificación EAC, resistencia al frío',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'Cables MT', 's2.r3c3': 'China', 's2.r3c4': 'Ensayos de tipo según norma nacional',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'Sistema de gestión de calidad', 's2.r4c3': 'Global', 's2.r4c4': 'Sistema auditado',
    's2.r5c1': 'CE', 's2.r5c2': 'Conformidad UE', 's2.r5c3': 'Europa', 's2.r5c4': 'Directivas de baja tensión y RoHS',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'Retardante de llama', 's2.r6c3': 'Global', 's2.r6c4': 'Ensayo de propagación vertical',
    's3.title': 'De la materia prima a la bobina ensayada',
    's3.p': 'Un recorrido controlado por cinco puntos de control de calidad.',
    's3.s1t': 'Inspección de materias primas', 's3.s1d': 'Cobre, aluminio y compounds verificados contra especificaciones.',
    's3.s2t': 'Ensayo del conductor', 's3.s2d': 'Sección, resistencia DC y cableado verificados.',
    's3.s3t': 'Controles de aislamiento y pantalla', 's3.s3d': 'Excentricidad, espesor y continuidad de pantalla monitoreados en línea.',
    's3.s4t': 'Descargas parciales y AT', 's3.s4d': 'Desempeño de tipo y soporte de alta tensión rutinario en cada bobina.',
    's3.s5t': 'Liberación y certificado', 's3.s5d': 'Las bobinas aprobadas reciben certificados y se embalan para exportación.',
    's4.title': 'Verificación en la que puede confiar',
    's4.p': 'La verificación independiente es bienvenida en cada etapa: inspección de terceros, ensayos de tipo presenciados y muestreo en sitio. Los compradores serios también pueden auditar la fábrica antes de pedir.',
    'faq.title': 'FAQ — calidad y certificación',
    'faq.q1': '¿Proporcionan informes de ensayos de tipo?', 'faq.a1': 'Sí — informes IEC/GOST/GB de nuestro laboratorio acreditado bajo pedido.',
    'faq.q2': '¿Permiten inspección de terceros?', 'faq.a2': 'Por supuesto — SGS, TÜV, BV o su inspector designado es bienvenido durante producción y antes del envío.',
    'faq.q3': '¿Cuál es el período de garantía?', 'faq.a3': 'Garantía de 12 meses contra defectos de fabricación; condiciones extendidas por contrato.',
    'faq.q4': '¿Ofrecen certificados para mercados EAC?', 'faq.a4': 'Sí — documentación EAC para Rusia, CEI y Asia Central se prepara con cada envío.',
    'faq.q5': '¿Cómo verifico la calidad antes de pedir?', 'faq.a5': 'Solicite muestras, informes de ensayo y auditoría de fábrica — recibimos a compradores serios en nuestra planta.',
    'cta.title': 'Solicite certificados e informes de ensayo',
    'cta.p': 'Indique la norma o certificación que su proyecto requiere — entregaremos los documentos y responderemos preguntas de calidad en 24 horas.',
}

I18N['tr'] = {
    'hero.eyebrow': 'Kalite Sistemi · Testler · Sertifikalar',
    'hero.title': 'Sertifikalı Kalite, <span class="accent">Her Makarada Test Edilir</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — ISO 9001 Kalite Sistemi · IEC / GOST / GB Standartları',
    'hero.lead': 'Kalite bir vaat değil bir süreçtir: ISO 9001 kalite yönetimi, hammadde izlenebilirliği, hat içi proses kontrolü ve sevkiyat öncesi her makarada %100 rutin test.',
    'hero.cta1': 'Test Raporu Talep Et', 'hero.cta2': 'Teknik Özellikler',
    's1.title': 'Kalite Sistemimize Genel Bakış',
    's1.p': 'Gelen hammaddeden test edilmiş makaraya kadar her aşama kontrol edilir, belgelenir ve doğrulanabilir.',
    's1.c1t': 'ISO 9001 Yönetim Sistemi', 's1.c1d': 'Tedarik, üretim ve muayeneyi kapsayan sertifikalı kalite yönetimi.',
    's1.c2t': 'Hammadde İzlenebilirliği', 's1.c2d': 'Bakır, alüminyum, XLPE bileşiği ve kılıf malzemeleri alımdan bitmiş makaraya kadar parti bazlı izlenir.',
    's1.c3t': 'Hat İçi Proses Kontrolü', 's1.c3d': 'Üretim sırasında iletken, izolasyon eksantrikliği, ekran ve kılıfın sürekli izlenmesi.',
    's1.c4t': '%100 Rutin Test', 's1.c4d': 'Her makara, sevkiyata çıkmadan önce IEC 60502-2\u2019ye göre rutin testten geçer.',
    's2.title': 'Standart ve Sertifikasyon Matrisi',
    's2.p': 'Pazarınızın gerektirdiği standartlara göre üretiriz — ve kanıtlayan sertifikaları sunarız.',
    's2.th1': 'Standart', 's2.th2': 'Kapsam', 's2.th3': 'Tipik Pazarlar', 's2.th4': 'Kilit Testler',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': '6–36 kV OG kablolar', 's2.r1c3': 'Küresel', 's2.r1c4': 'Tip ve rutin testler, kısmi deşarj',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'OG güç kabloları', 's2.r2c3': 'Rusya, BDT, Orta Asya', 's2.r2c4': 'EAC sertifikasyonu, soğuğa dayanıklılık',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'OG kablolar', 's2.r3c3': 'Çin', 's2.r3c4': 'Ulusal standarda göre tip testleri',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'Kalite yönetim sistemi', 's2.r4c3': 'Küresel', 's2.r4c4': 'Denetlenmiş yönetim sistemi',
    's2.r5c1': 'CE', 's2.r5c2': 'AB uygunluğu', 's2.r5c3': 'Avrupa', 's2.r5c4': 'Alçak gerilim ve RoHS direktifleri',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'Alev geciktirme', 's2.r6c3': 'Küresel', 's2.r6c4': 'Dikey alev yayılım testi',
    's3.title': 'Hammaddeden Test Edilmiş Makaraya',
    's3.p': 'Beş kalite kontrol noktasından geçen kontrollü bir yolculuk.',
    's3.s1t': 'Hammadde Muayenesi', 's3.s1d': 'Gelen bakır, alüminyum ve bileşikler spesifikasyonlara göre doğrulanır.',
    's3.s2t': 'İletken Testi', 's3.s2d': 'Kesit, DC direnç ve örgü doğrulanır.',
    's3.s3t': 'İzolasyon ve Ekran Kontrolleri', 's3.s3d': 'Eksantriklik, kalınlık ve ekran sürekliliği hat içinde izlenir.',
    's3.s4t': 'Kısmi Deşarj ve YG Testleri', 's3.s4d': 'Tip testli performans ve her makarada rutin yüksek gerilim dayanımı.',
    's3.s5t': 'Serbest Bırakma ve Sertifika', 's3.s5d': 'Onaylanan makaralar sertifika alır ve ihracata hazırlanır.',
    's4.title': 'Güvenebileceğiniz Doğrulama',
    's4.p': 'Her aşamada bağımsız doğrulama memnuniyetle karşılanır: üçüncü taraf muayenesi, tanıklı tip testleri ve sahada numune alma. Ciddi alıcılar siparişten önce fabrika denetimi de ayarlayabilir.',
    'faq.title': 'SSS — Kalite ve Sertifikasyon',
    'faq.q1': 'Tip test raporları sağlıyor musunuz?', 'faq.a1': 'Evet — akredite laboratuvarımızdan IEC/GOST/GB tip test raporları talep üzerine.',
    'faq.q2': 'Üçüncü taraf muayenesine izin veriyor musunuz?', 'faq.a2': 'Kesinlikle — SGS, TÜV, BV veya belirlediğiniz müfettiş üretim sırasında ve sevkiyat öncesi memnuniyetle karşılanır.',
    'faq.q3': 'Garanti süresi nedir?', 'faq.a3': 'Üretim hatalarına karşı 12 ay garanti; uzatılmış şartlar sözleşmeyle kararlaştırılabilir.',
    'faq.q4': 'EAC pazarları için sertifika sunuyor musunuz?', 'faq.a4': 'Evet — Rusya, BDT ve Orta Asya için EAC beyan/sertifikasyon belgeleri her sevkiyatla hazırlanır.',
    'faq.q5': 'Sipariş öncesi kaliteyi nasıl doğrularım?', 'faq.a5': 'Numune, test raporları ve fabrika denetimi talep edin — ciddi alıcıları tesisimizde ağırlarız.',
    'cta.title': 'Sertifika ve Test Raporu Talep Edin',
    'cta.p': 'Projenizin hangi standart veya sertifikayı gerektirdiğini söyleyin — ilgili belgeleri sunar ve kalite sorularınızı 24 saat içinde yanıtlarız.',
}

I18N['pt'] = {
    'hero.eyebrow': 'Sistema de qualidade · Ensaios · Certificações',
    'hero.title': 'Qualidade certificada, <span class="accent">ensaiada em cada bobina</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — sistema de qualidade ISO 9001 · normas IEC / GOST / GB',
    'hero.lead': 'Qualidade não é promessa, é processo: gestão ISO 9001, rastreabilidade de matérias-primas, controle em linha e 100% de ensaios de rotina em cada bobina antes do embarque.',
    'hero.cta1': 'Solicitar relatórios de ensaio', 'hero.cta2': 'Ver especificações',
    's1.title': 'Nosso sistema de qualidade em resumo',
    's1.p': 'Da matéria-prima à bobina ensaiada, cada etapa é controlada, documentada e verificável.',
    's1.c1t': 'Sistema de gestão ISO 9001', 's1.c1d': 'Gestão de qualidade certificada cobrindo compras, produção e inspeção.',
    's1.c2t': 'Rastreabilidade de matérias-primas', 's1.c2d': 'Cobre, alumínio, compound XLPE e coberturas rastreados por lote, da recepção à bobina final.',
    's1.c3t': 'Controle de processo em linha', 's1.c3d': 'Monitoramento contínuo do condutor, excentricidade do isolamento, tela e cobertura.',
    's1.c4t': '100% ensaios de rotina', 's1.c4d': 'Cada bobina passa por ensaios de rotina conforme IEC 60502-2 antes da liberação.',
    's2.title': 'Matriz de normas e certificações',
    's2.p': 'Fabricamos conforme as normas que seu mercado exige — e entregamos os certificados que comprovam.',
    's2.th1': 'Norma', 's2.th2': 'Escopo', 's2.th3': 'Mercados típicos', 's2.th4': 'Ensaios-chave',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': 'Cabos MT 6–36 kV', 's2.r1c3': 'Global', 's2.r1c4': 'Ensaios de tipo e rotina, descargas parciais',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'Cabos MT', 's2.r2c3': 'Rússia, CEI, Ásia Central', 's2.r2c4': 'Certificação EAC, resistência ao frio',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'Cabos MT', 's2.r3c3': 'China', 's2.r3c4': 'Ensaios de tipo conforme norma nacional',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'Sistema de gestão da qualidade', 's2.r4c3': 'Global', 's2.r4c4': 'Sistema auditado',
    's2.r5c1': 'CE', 's2.r5c2': 'Conformidade UE', 's2.r5c3': 'Europa', 's2.r5c4': 'Diretivas de baixa tensão e RoHS',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'Retardante de chama', 's2.r6c3': 'Global', 's2.r6c4': 'Ensaio de propagação vertical',
    's3.title': 'Da matéria-prima à bobina ensaiada',
    's3.p': 'Uma jornada controlada por cinco pontos de controle de qualidade.',
    's3.s1t': 'Inspeção de matérias-primas', 's3.s1d': 'Cobre, alumínio e compostos verificados contra especificações.',
    's3.s2t': 'Ensaio do condutor', 's3.s2d': 'Seção, resistência CC e encordoamento verificados.',
    's3.s3t': 'Controles de isolamento e tela', 's3.s3d': 'Excentricidade, espessura e continuidade da tela monitoradas em linha.',
    's3.s4t': 'Descargas parciais e AT', 's3.s4d': 'Desempenho de tipo e suporte de alta tensão de rotina em cada bobina.',
    's3.s5t': 'Liberação e certificado', 's3.s5d': 'Bobinas aprovadas recebem certificados e são embaladas para exportação.',
    's4.title': 'Verificação em que você pode confiar',
    's4.p': 'A verificação independente é bem-vinda em cada etapa: inspeção por terceiros, ensaios de tipo testemunhados e amostragem no local. Compradores sérios também podem auditar a fábrica antes de pedir.',
    'faq.title': 'FAQ — qualidade e certificação',
    'faq.q1': 'Vocês fornecem relatórios de ensaios de tipo?', 'faq.a1': 'Sim — relatórios IEC/GOST/GB de nosso laboratório acreditado sob pedido.',
    'faq.q2': 'Vocês permitem inspeção de terceiros?', 'faq.a2': 'Absolutamente — SGS, TÜV, BV ou seu inspetor designado é bem-vindo durante a produção e antes do embarque.',
    'faq.q3': 'Qual o período de garantia?', 'faq.a3': 'Garantia de 12 meses contra defeitos de fabricação; condições estendidas por contrato.',
    'faq.q4': 'Vocês oferecem certificados para mercados EAC?', 'faq.a4': 'Sim — documentação EAC para Rússia, CEI e Ásia Central é preparada com cada envio.',
    'faq.q5': 'Como verifico a qualidade antes de pedir?', 'faq.a5': 'Solicite amostras, relatórios de ensaio e auditoria de fábrica — recebemos compradores sérios em nossa planta.',
    'cta.title': 'Solicite certificados e relatórios de ensaio',
    'cta.p': 'Informe qual norma ou certificação seu projeto exige — forneceremos os documentos e responderemos perguntas de qualidade em 24 horas.',
}

I18N['mn'] = {
    'hero.eyebrow': 'Чанарын систем · Туршилт · Гэрчилгээ',
    'hero.title': 'Гэрчилгээжсэн чанар, <span class="accent">ороомог бүрд шалгагдсан</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — ISO 9001 чанарын систем · IEC / GOST / GB стандарт',
    'hero.lead': 'Чанар бол амлалт биш, үйл явц: ISO 9001 чанарын менежмент, түүхий эдийн мөрдөлт, шугамын процессын хяналт, ачихаас өмнө ороомог бүрт 100% ердийн туршилт.',
    'hero.cta1': 'Туршилтын тайлан авах', 'hero.cta2': 'Техникийн үзүүлэлт',
    's1.title': 'Манай чанарын систем товч',
    's1.p': 'Орж ирсэн түүхий эдээс шалгагдсан ороомог хүртэл үе шат бүр хянагдаж, баримтжиж, баталгаажиж байдаг.',
    's1.c1t': 'ISO 9001 удирдлагын систем', 's1.c1d': 'Худалдан авалт, үйлдвэрлэл, хяналтыг хамарсан гэрчилгээжсэн чанарын менежмент.',
    's1.c2t': 'Түүхий эдийн мөрдөлт', 's1.c2d': 'Мэс, хөнгөн цагаан, XLPE нэгдэл, хүрдэлийн материал хүлээн авалтаас бэлэн ороомог хүртэл багцаар хянагдана.',
    's1.c3t': 'Шугамын процессын хяналт', 's1.c3d': 'Үйлдвэрлэлийн үед дамжуулагч, изоляцийн эксцентрит, дэлгэц, хүрдэлийг тасралтгүй хянана.',
    's1.c4t': '100% ердийн туршилт', 's1.c4d': 'Ороомог бүр ачихаас өмнө IEC 60502-2 дагуу ердийн туршилтад орно.',
    's2.title': 'Стандарт ба гэрчилгээний матриц',
    's2.p': 'Таны зах зээлийн шаардсан стандартаар үйлдвэрлэнэ — үүнийг батлах гэрчилгээг өгнө.',
    's2.th1': 'Стандарт', 's2.th2': 'Хамрах хүрээ', 's2.th3': 'Гол зах зээл', 's2.th4': 'Гол туршилтууд',
    's2.r1c1': 'IEC 60502-2', 's2.r1c2': '6–36 кВ ДХ кабел', 's2.r1c3': 'Дэлхий', 's2.r1c4': 'Төрөл ба ердийн туршилт, хэсэгчилсэн цэнэг',
    's2.r2c1': 'GOST 31996', 's2.r2c2': 'ДХ цахилгаан кабел', 's2.r2c3': 'Орос, ТУХН, Төв Ази', 's2.r2c4': 'EAC гэрчилгээ, хүйтэнд тэсвэр',
    's2.r3c1': 'GB/T 12706', 's2.r3c2': 'ДХ кабел', 's2.r3c3': 'Хятад', 's2.r3c4': 'Үндэсний стандартын төрлийн туршилт',
    's2.r4c1': 'ISO 9001', 's2.r4c2': 'Чанарын удирдлагын систем', 's2.r4c3': 'Дэлхий', 's2.r4c4': 'Аудитад орсон удирдлагын систем',
    's2.r5c1': 'CE', 's2.r5c2': 'ЕХ-ны нийцэл', 's2.r5c3': 'Европ', 's2.r5c4': 'Бага хүчдэл ба RoHS заавар',
    's2.r6c1': 'IEC 60332-1', 's2.r6c2': 'Галд тэсвэртэй байдал', 's2.r6c3': 'Дэлхий', 's2.r6c4': 'Босоо дөл тархалтын туршилт',
    's3.title': 'Түүхий эдээс шалгагдсан ороомог хүртэл',
    's3.p': 'Таван чанарын хяналтын цэгийг дайрсан хяналттай зам.',
    's3.s1t': 'Түүхий эдийн хяналт', 's3.s1d': 'Орж ирсэн мэс, хөнгөн цагаан, нэгдлийг үзүүлэлтээр баталгаажуулна.',
    's3.s2t': 'Дамжуулагчийн туршилт', 's3.s2d': 'Хөндлөн огтлол, тогтмол гүйдэл эсэргүүцэл, эрчилт шалгагдана.',
    's3.s3t': 'Изоляц ба дэлгэцийн шалгалт', 's3.s3d': 'Эксцентрит, зузаан, дэлгэцийн тасралтгүй байдлыг шугам дээр хянана.',
    's3.s4t': 'Хэсэгчилсэн цэнэг ба өндөр хүчдэл', 's3.s4d': 'Төрлийн туршилтын гүйцэтгэл, ороомог бүрд ердийн өндөр хүчдэлийн туршилт.',
    's3.s5t': 'Гаргалт ба гэрчилгээ', 's3.s5d': 'Зөвшөөрөгдсөн ороомог гэрчилгээ авч, экспортод савлагдана.',
    's4.title': 'Итгэж болох баталгаажуулалт',
    's4.p': 'Үе шат бүрд бие даасан баталгаажуулалтыг угтаж авна: гуравдагч этгээдийн хяналт, төрлийн туршилтад байлцах, талбайд дээж авах. Ноён худалдан авагчид захиалгаас өмнө үйлдвэрийн аудит ч хийлгэж болно.',
    'faq.title': 'Түгээмэл асуулт — чанар ба гэрчилгээ',
    'faq.q1': 'Төрлийн туршилтын тайлан өгдөг үү?', 'faq.a1': 'Тийм — магадлан итгэмжлэгдсэн лабораторийн IEC/GOST/GB тайланг хүсэлтээр.',
    'faq.q2': 'Гуравдагч этгээдийн хяналтыг зөвшөөрдөг үү?', 'faq.a2': 'Бүрэн — SGS, TÜV, BV эсвэл таны томилсон байцаагчийг үйлдвэрлэлийн үед ба ачихаас өмнө угтаж авна.',
    'faq.q3': 'Баталгаа хугацаа хэд вэ?', 'faq.a3': 'Үйлдвэрлэлийн согогт 12 сарын баталгаа; уртасгасан нөхцөлийг гэрээгээр тохиролцоно.',
    'faq.q4': 'EAC зах зээлд гэрчилгээ өгдөг үү?', 'faq.a4': 'Тийм — Орос, ТУХН, Төв Азид зориулсан EAC баримт ачаа болгонд бэлтгэгдэнэ.',
    'faq.q5': 'Захиалгаас өмнө чанарыг хэрхэн шалгах вэ?', 'faq.a5': 'Дээж, туршилтын тайлан, үйлдвэрийн аудит хүснэ үү — ноён худалдан авагчдыг үйлдвэрт угтаж авна.',
    'cta.title': 'Гэрчилгээ ба туршилтын тайлан авах',
    'cta.p': 'Төсөлдөө ямар стандарт эсвэл гэрчилгээ хэрэгтэйг хэлнэ үү — 24 цагийн дотор холбогдох баримт, чанарын асуултад хариу өгнө.',
}
