# -*- coding: utf-8 -*-
"""Page data: solutions2.html — Turnkey Cable Solutions (一站式电缆解决方案), 11 languages."""

CFG = {
    'file': 'solutions2.html',
    'cta2_href': 'https://ouzcable.com/export.html',
    'title': 'Turnkey Cable Solutions | Wind Solar Data Center Mining Projects — OUZHI Cable 欧智电缆 | 一站式电缆解决方案',
    'desc': 'Complete cable solutions from OUZHI Cable (欧智电缆) source factory for wind power, solar PV, data center/AI computing, industrial & mining projects. Cable selection, jointing kits, accessory supply, technical support and on-time delivery worldwide. Contact: info@ouzcable.com | +998 99 851 6999.',
    'keywords': 'cable solutions wind farm, solar PV cable solution, data center cable solution, AI computing power cable, mining cable solution, MV cable project supply, cable jointing accessories, cable technical support, turnkey cable supply, renewable energy cable China, OUZHI Cable, 欧智电缆, 电缆解决方案, 风电电缆, 光伏电缆, 数据中心电缆',
    'ld_headline': 'Turnkey Cable Solutions for Energy, Data Center and Industry — OUZHI Cable',
    'ld_desc': 'Complete medium-voltage cable supply for wind, solar, data center and mining projects: engineering support, accessories, jointing guidance and on-time delivery. Contact info@ouzcable.com | +998 99 851 6999.',
    'sections': [
        {'type': 'hero'},
        {'type': 'cards', 'title': 's1.title', 'p': 's1.p', 'c': 's1.c'},
        {'type': 'table', 'title': 's2.title', 'p': 's2.p', 'th': 's2.th', 'cols': 4, 'rows': [
            ['s2.r1c1', 's2.r1c2', 's2.r1c3', 's2.r1c4'],
            ['s2.r2c1', 's2.r2c2', 's2.r2c3', 's2.r2c4'],
            ['s2.r3c1', 's2.r3c2', 's2.r3c3', 's2.r3c4'],
            ['s2.r4c1', 's2.r4c2', 's2.r4c3', 's2.r4c4'],
        ]},
        {'type': 'steps', 'title': 's3.title', 'p': 's3.p', 's': 's3.s', 'n': 5},
        {'type': 'highlight', 'title': 's4.title', 'p': 's4.p'},
        {'type': 'faq', 'title': 'faq.title', 'n': 5},
        {'type': 'cta'}
    ],
}

I18N = {}

I18N['en'] = {
    'hero.eyebrow': 'Turnkey Supply · Engineering Support · 2026',
    'hero.title': 'Complete Cable Solutions for <span class="accent">Energy, Data Center & Industry</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — One Source for Cable, Accessories & Support',
    'hero.lead': 'One inquiry, one supply chain: medium-voltage cables, accessories, jointing guidance and engineering support for wind farms, solar PV plants, data centers and industrial projects — delivered on time, worldwide.',
    'hero.cta1': 'Start Your Project', 'hero.cta2': 'Factory & Export Info',
    's1.title': 'Solutions Across Four Core Sectors',
    's1.p': 'Each sector has its own electrical, thermal and mechanical demands — our engineering team helps you select the right cable construction the first time.',
    's1.c1t': 'Wind Power Projects', 's1.c1d': 'Tower-to-grid MV cables with flexible conductors, excellent cold and UV resistance and reliable termination support.',
    's1.c2t': 'Solar PV Plants', 's1.c2d': 'PV strings, DC circuits and MV collection cables with high ambient-temperature rating and long service life.',
    's1.c3t': 'Data Centers & AI Computing', 's1.c3d': 'High-power 35 kV feeder cables for AI computing clusters — low-loss, fire-retardant and future-proof.',
    's1.c4t': 'Industrial & Mining', 's1.c4d': 'Armoured cables for harsh environments: abrasion, oil and moisture resistant for mining and heavy industry.',
    's2.title': 'Solution Scope per Sector',
    's2.p': 'From project engineering to installation guidance — the complete scope we cover for each sector.',
    's2.th1': 'Sector', 's2.th2': 'Cable Types', 's2.th3': 'Add-ons', 's2.th4': 'Support',
    's2.r1c1': 'Wind', 's2.r1c2': 'MV 12/20, 26/35 kV flexible', 's2.r1c3': 'Terminations, joint kits', 's2.r1c4': 'Layout & rating calculation',
    's2.r2c1': 'Solar PV', 's2.r2c2': 'PV1-F, DC cables, MV collection', 's2.r2c3': 'DC connectors, earthing', 's2.r2c4': 'String & plant design advice',
    's2.r3c1': 'Data Center / AI', 's2.r3c2': '35 kV LSZH feeders, control cables', 's2.r3c3': 'Busway links, monitoring', 's2.r3c4': 'Redundancy & fire-safety specs',
    's2.r4c1': 'Mining & Industry', 's2.r4c2': 'Armoured SWA, rubber cables', 's2.r4c3': 'Glands, couplers', 's2.r4c4': 'Site-specific hardening',
    's3.title': 'How a Project Supply Works',
    's3.p': 'A structured path from your inquiry to site installation — supported at every step.',
    's3.s1t': 'Project Inquiry', 's3.s1d': 'Share drawings, voltage and load data — our engineers confirm the cable schedule.',
    's3.s2t': 'Solution & Quotation', 's3.s2d': 'Cable schedule, accessories list and factory quotation delivered together.',
    's3.s3t': 'Production & Inspection', 's3.s3d': 'Cables manufactured and tested; photos, reports and witness inspection available.',
    's3.s4t': 'Logistics & Customs', 's3.s4d': 'Export documentation, shipping and customs support to your destination.',
    's3.s5t': 'Installation Support', 's3.s5d': 'Jointing and termination guidance by experienced engineers, remote or on site.',
    's4.title': 'Engineering Support Included',
    's4.p': 'Every project supply includes cable selection assistance, cross-section and voltage-drop checks, accessory matching and installation guidance. Send your drawings and load data — our engineers will prepare the cable schedule for you.',
    'faq.title': 'FAQ — Project Solutions',
    'faq.q1': 'Can you supply the complete cable schedule?', 'faq.a1': 'Yes — share your project drawings and load data, and we will propose the full cable and accessory schedule.',
    'faq.q2': 'Do you provide jointing and termination kits?', 'faq.a2': 'Yes — compatible joint and termination kits are supplied with the cables, matched to voltage class and conductor.',
    'faq.q3': 'Can you help with cable sizing?', 'faq.a3': 'Yes — our engineers provide cross-section selection, voltage-drop and ampacity checks free of charge.',
    'faq.q4': 'Do you support on-site installation?', 'faq.a4': 'We provide installation and jointing guidance remotely or with on-site engineers for larger projects.',
    'faq.q5': 'What about spare cables for maintenance?', 'faq.a5': 'We recommend ordering spare drums with the main shipment — additional orders are produced quickly from our lines.',
    'cta.title': 'Start Your Cable Project Today',
    'cta.p': 'Send your drawings and requirements — our engineering and export teams will reply within 24 hours with a complete solution and quotation.',
}

I18N['zh'] = {
    'hero.eyebrow': '一站式供货 · 工程支持 · 2026',
    'hero.title': '<span class="accent">能源、数据中心与工业</span>完整电缆解决方案',
    'hero.sub': '欧智电缆（OUZHI Cable）— 电缆、附件与支持一站式来源',
    'hero.lead': '一次询盘、一条供应链：面向风电、光伏、数据中心与工业项目的中压电缆、附件、接头指导与工程支持——准时交付，覆盖全球。',
    'hero.cta1': '启动您的项目', 'hero.cta2': '工厂与出口信息',
    's1.title': '四大核心行业解决方案',
    's1.p': '每个行业都有各自的电气、热力与机械要求——我们的工程团队帮您一次选对电缆结构。',
    's1.c1t': '风电项目', 's1.c1d': '塔筒到电网的中压电缆：柔性导体、优异的耐寒与抗紫外线性能、可靠的终端支持。',
    's1.c2t': '光伏电站', 's1.c2d': '光伏组串、直流回路与中压集电电缆：耐高温环境、长使用寿命。',
    's1.c3t': '数据中心与AI算力', 's1.c3d': '面向AI算力集群的大功率35kV馈电电缆——低损耗、阻燃、面向未来。',
    's1.c4t': '工矿行业', 's1.c4d': '严苛环境用铠装电缆：耐磨、耐油、防潮，适用于矿山与重工业。',
    's2.title': '各行业解决方案范围',
    's2.p': '从项目设计到安装指导——我们为每个行业提供的完整范围。',
    's2.th1': '行业', 's2.th2': '电缆类型', 's2.th3': '配套附件', 's2.th4': '支持',
    's2.r1c1': '风电', 's2.r1c2': '12/20、26/35kV 柔性中压电缆', 's2.r1c3': '终端、接头套件', 's2.r1c4': '布置与载流量计算',
    's2.r2c1': '光伏', 's2.r2c2': 'PV1-F、直流电缆、中压集电', 's2.r2c3': '直流连接器、接地', 's2.r2c4': '组串与电站设计建议',
    's2.r3c1': '数据中心 / AI', 's2.r3c2': '35kV LSZH 馈电、控制电缆', 's2.r3c3': '母线连接、监控', 's2.r3c4': '冗余与防火规范',
    's2.r4c1': '矿山与工业', 's2.r4c2': '铠装 SWA、橡胶电缆', 's2.r4c3': '格兰头、连接器', 's2.r4c4': '现场定制加固',
    's3.title': '项目供货流程',
    's3.p': '从询盘到现场安装的结构化路径——每一步都有支持。',
    's3.s1t': '项目询盘', 's3.s1d': '提供图纸、电压与负荷数据——工程师确认电缆清单。',
    's3.s2t': '方案与报价', 's3.s2d': '电缆清单、附件清单与工厂报价一并交付。',
    's3.s3t': '生产与检验', 's3.s3d': '电缆制造并检测；提供照片、报告与见证检验。',
    's3.s4t': '物流与报关', 's3.s4d': '出口文件、运输与目的国报关支持。',
    's3.s5t': '安装支持', 's3.s5d': '资深工程师提供远程或现场接头与终端指导。',
    's4.title': '工程支持全程包含',
    's4.p': '每次项目供货均包含电缆选型协助、截面与压降校核、附件匹配与安装指导。发送您的图纸与负荷数据——工程师将为您准备完整电缆清单。',
    'faq.title': '常见问题 — 项目解决方案',
    'faq.q1': '能否供应完整电缆清单？', 'faq.a1': '可以。提供项目图纸与负荷数据，我们将给出完整电缆与附件清单。',
    'faq.q2': '是否提供接头与终端套件？', 'faq.a2': '提供。与电缆配套、按电压等级与导体匹配的接头与终端套件。',
    'faq.q3': '能否协助电缆选型？', 'faq.a3': '可以。工程师免费提供截面选择、压降与载流量校核。',
    'faq.q4': '是否支持现场安装？', 'faq.a4': '我们提供远程安装与接头指导；大型项目可安排现场工程师。',
    'faq.q5': '维护备用电缆怎么办？', 'faq.a5': '建议随主批订购备用盘；后续订单可从生产线快速生产。',
    'cta.title': '今天就启动您的电缆项目',
    'cta.p': '发送图纸与需求——工程与出口团队将在24小时内回复完整方案与报价。',
}

I18N['ru'] = {
    'hero.eyebrow': 'Комплексные поставки · Инженерная поддержка · 2026',
    'hero.title': 'Полные кабельные решения для <span class="accent">энергетики, ЦОД и промышленности</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — единый источник: кабель, аксессуары и поддержка',
    'hero.lead': 'Один запрос — одна цепочка поставок: кабели среднего напряжения, аксессуары, рекомендации по монтажу и инженерная поддержка для ветропарков, солнечных станций, ЦОД и промышленных проектов — вовремя, по всему миру.',
    'hero.cta1': 'Начать проект', 'hero.cta2': 'Завод и экспорт',
    's1.title': 'Решения для четырёх ключевых секторов',
    's1.p': 'У каждого сектора свои электрические, тепловые и механические требования — наша инженерная команда поможет выбрать правильную конструкцию кабеля с первого раза.',
    's1.c1t': 'Ветроэнергетика', 's1.c1d': 'Кабели СН от башни до сети: гибкие жилы, отличная стойкость к холоду и УФ, надёжный монтаж оконцеваний.',
    's1.c2t': 'Солнечные электростанции', 's1.c2d': 'PV-цепочки, цепи постоянного тока и кабели СН с высокой рабочей температурой и долгим сроком службы.',
    's1.c3t': 'ЦОД и ИИ-вычисления', 's1.c3d': 'Мощные питающие кабели 35 кВ для ИИ-кластеров — низкие потери, огнестойкость, готовность к будущему.',
    's1.c4t': 'Промышленность и горное дело', 's1.c4d': 'Бронированные кабели для жёстких условий: стойкость к истиранию, маслу и влаге.',
    's2.title': 'Объём решений по секторам',
    's2.p': 'От проектирования до шеф-монтажа — полный объём для каждого сектора.',
    's2.th1': 'Сектор', 's2.th2': 'Типы кабелей', 's2.th3': 'Аксессуары', 's2.th4': 'Поддержка',
    's2.r1c1': 'Ветер', 's2.r1c2': '12/20, 26/35 кВ гибкие', 's2.r1c3': 'Оконцевания, муфты', 's2.r1c4': 'Расчёт трассы и токовой нагрузки',
    's2.r2c1': 'Солнце', 's2.r2c2': 'PV1-F, кабели DC, СН', 's2.r2c3': 'DC-коннекторы, заземление', 's2.r2c4': 'Рекомендации по проектированию',
    's2.r3c1': 'ЦОД / ИИ', 's2.r3c2': '35 кВ LSZH, контрольные', 's2.r3c3': 'Шинопроводы, мониторинг', 's2.r3c4': 'Резервирование и пожаробезопасность',
    's2.r4c1': 'Горное дело и пром.', 's2.r4c2': 'Бронированные SWA, резиновые', 's2.r4c3': 'Кабельные вводы, соединители', 's2.r4c4': 'Усиление под объект',
    's3.title': 'Как работают проектные поставки',
    's3.p': 'Структурированный путь от запроса до монтажа — поддержка на каждом шаге.',
    's3.s1t': 'Проектный запрос', 's3.s1d': 'Пришлите чертежи, напряжение и нагрузки — инженеры подтвердят кабельную ведомость.',
    's3.s2t': 'Решение и котировка', 's3.s2d': 'Кабельная ведомость, список аксессуаров и котировка завода — вместе.',
    's3.s3t': 'Производство и контроль', 's3.s3d': 'Изготовление и испытания; фото, отчёты, присутствие при контроле.',
    's3.s4t': 'Логистика и таможня', 's3.s4d': 'Экспортная документация, доставка и таможенная поддержка.',
    's3.s5t': 'Шеф-монтаж', 's3.s5d': 'Рекомендации по монтажу муфт и оконцеваний, дистанционно или на объекте.',
    's4.title': 'Инженерная поддержка включена',
    's4.p': 'Каждая поставка включает помощь в выборе кабеля, проверку сечения и падения напряжения, подбор аксессуаров и рекомендации по монтажу. Пришлите чертежи и данные нагрузок — инженеры подготовят кабельную ведомость.',
    'faq.title': 'FAQ — проектные решения',
    'faq.q1': 'Можете ли поставить полную кабельную ведомость?', 'faq.a1': 'Да — пришлите чертежи и данные нагрузок, предложим полную ведомость кабелей и аксессуаров.',
    'faq.q2': 'Поставляете ли муфты и оконцевания?', 'faq.a2': 'Да — совместимые комплекты муфт и оконцеваний поставляются с кабелем, под класс напряжения и сечение.',
    'faq.q3': 'Помогаете ли с выбором сечения?', 'faq.a3': 'Да — инженеры бесплатно выполнят подбор сечения, проверку падения напряжения и токовой нагрузки.',
    'faq.q4': 'Поддерживаете ли монтаж на объекте?', 'faq.a4': 'Предоставляем рекомендации по монтажу и соединению дистанционно; для крупных проектов — инженеры на объекте.',
    'faq.q5': 'Как заказать резервные кабели?', 'faq.a5': 'Рекомендуем заказывать резервные барабаны с основной партией; дополнительные заказы производятся быстро.',
    'cta.title': 'Начните свой кабельный проект сегодня',
    'cta.p': 'Пришлите чертежи и требования — инженерная и экспортная команды ответят в течение 24 часов с полным решением и котировкой.',
}

I18N['ar'] = {
    'hero.eyebrow': 'توريد متكامل · دعم هندسي · 2026',
    'hero.title': 'حلول كابلات شاملة <span class="accent">للطاقة ومراكز البيانات والصناعة</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — مصدر واحد للكابلات والملحقات والدعم',
    'hero.lead': 'استفسار واحد، سلسلة توريد واحدة: كابلات الجهد المتوسط والملحقات وإرشادات الوصل والدعم الهندسي لمزارع الرياح ومحطات الطاقة الشمسية ومراكز البيانات والمشاريع الصناعية — في الوقت المحدد حول العالم.',
    'hero.cta1': 'ابدأ مشروعك', 'hero.cta2': 'المصنع والتصدير',
    's1.title': 'حلول عبر أربعة قطاعات رئيسية',
    's1.p': 'لكل قطاع متطلباته الكهربائية والحرارية والميكانيكية — فريقنا الهندسي يساعدك على اختيار بنية الكابل الصحيحة من المرة الأولى.',
    's1.c1t': 'مشاريع طاقة الرياح', 's1.c1d': 'كابلات متوسطة الجهد من البرج إلى الشبكة بموصلات مرنة ومقاومة ممتازة للبرد والأشعة فوق البنفسجية.',
    's1.c2t': 'محطات الطاقة الشمسية', 's1.c2d': 'سلاسل الألواح ودوائر التيار المستمر وكابلات التجميع المتوسطة بمعدل حرارة مرتفع وعمر طويل.',
    's1.c3t': 'مراكز البيانات وحوسبة الذكاء الاصطناعي', 's1.c3d': 'كابلات تغذية 35 ك.ف عالية القدرة لمجموعات الحوسبة — خسارة منخفضة ومقاومة للهب.',
    's1.c4t': 'الصناعة والتعدين', 's1.c4d': 'كابلات مدرعة للبيئات القاسية: مقاومة للتآكل والزيوت والرطوبة.',
    's2.title': 'نطاق الحلول لكل قطاع',
    's2.p': 'من هندسة المشروع إلى إرشادات التركيب — النطاق الكامل الذي نغطيه لكل قطاع.',
    's2.th1': 'القطاع', 's2.th2': 'أنواع الكابلات', 's2.th3': 'الإضافات', 's2.th4': 'الدعم',
    's2.r1c1': 'الرياح', 's2.r1c2': 'مرنة 12/20 و26/35 ك.ف', 's2.r1c3': 'نهايات وأطقم وصل', 's2.r1c4': 'حساب التخطيط والتحميل',
    's2.r2c1': 'الطاقة الشمسية', 's2.r2c2': 'PV1-F وكابلات DC وتجميع', 's2.r2c3': 'موصلات DC والتأريض', 's2.r2c4': 'نصائح تصميم المحطة',
    's2.r3c1': 'مراكز البيانات / الذكاء الاصطناعي', 's2.r3c2': 'تغذية 35 ك.ف LSZH وتحكم', 's2.r3c3': 'وصلات قضبان ومراقبة', 's2.r3c4': 'مواصفات التكرار والسلامة',
    's2.r4c1': 'التعدين والصناعة', 's2.r4c2': 'مدرعة SWA ومطاطية', 's2.r4c3': 'موانع تسرب ووصلات', 's2.r4c4': 'تقوية حسب الموقع',
    's3.title': 'كيف تعمل توريدات المشاريع',
    's3.p': 'مسار منظم من استفسارك إلى التركيب في الموقع — بدعم في كل خطوة.',
    's3.s1t': 'استفسار المشروع', 's3.s1d': 'شارك الرسومات والجهد وبيانات الحمل — يؤكد المهندسون جدول الكابلات.',
    's3.s2t': 'الحل والسعر', 's3.s2d': 'جدول الكابلات وقائمة الملحقات وسعر المصنع معاً.',
    's3.s3t': 'الإنتاج والفحص', 's3.s3d': 'تصنيع واختبار الكابلات؛ صور وتقارير وفحص بالحضور.',
    's3.s4t': 'اللوجستيات والجمارك', 's3.s4d': 'وثائق التصدير والشحن والدعم الجمركي إلى وجهتك.',
    's3.s5t': 'دعم التركيب', 's3.s5d': 'إرشادات الوصل والنهايات من مهندسين خبراء، عن بعد أو في الموقع.',
    's4.title': 'الدعم الهندسي مشمول',
    's4.p': 'كل توريد مشروع يشمل المساعدة في اختيار الكابلات وفحص المقطع وهبوط الجهد ومطابقة الملحقات وإرشادات التركيب. أرسل رسوماتك وبيانات الحمل — سيعد المهندسون جدول الكابلات لك.',
    'faq.title': 'الأسئلة الشائعة — حلول المشاريع',
    'faq.q1': 'هل يمكنكم توريد جدول الكابلات الكامل؟', 'faq.a1': 'نعم — شارك رسومات المشروع وبيانات الحمل وسنقترح جدول الكابلات والملحقات الكامل.',
    'faq.q2': 'هل توفرون أطقم الوصل والنهايات؟', 'faq.a2': 'نعم — تُورَّد أطقم وصل ونهايات متوافقة مع الكابلات، مطابقة لدرجة الجهد والموصل.',
    'faq.q3': 'هل تساعدون في اختيار مقطع الكابل؟', 'faq.a3': 'نعم — مهندسونا يقدمون فحص اختيار المقطع وهبوط الجهد وسعة التحميل مجاناً.',
    'faq.q4': 'هل تدعمون التركيب في الموقع؟', 'faq.a4': 'نقدم إرشادات التركيب والوصل عن بعد أو بمهندسين في الموقع للمشاريع الكبيرة.',
    'faq.q5': 'ماذا عن الكابلات الاحتياطية للصيانة؟', 'faq.a5': 'نوصي بطلب براميل احتياطية مع الشحنة الرئيسية — الطلبات الإضافية تُنتج بسرعة من خطوطنا.',
    'cta.title': 'ابدأ مشروع الكابلات اليوم',
    'cta.p': 'أرسل رسوماتك ومتطلباتك — يرد فريقا الهندسة والتصدير خلال 24 ساعة بحل كامل وسعر.',
}

I18N['fr'] = {
    'hero.eyebrow': 'Fourniture clé en main · Support ingénierie · 2026',
    'hero.title': 'Solutions câbles complètes pour <span class="accent">l\u2019énergie, les data centers et l\u2019industrie</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — une seule source : câbles, accessoires et support',
    'hero.lead': 'Une demande, une chaîne d\u2019approvisionnement : câbles moyenne tension, accessoires, conseils de jonction et support ingénierie pour parcs éoliens, centrales solaires, data centers et projets industriels — livrés à temps, partout dans le monde.',
    'hero.cta1': 'Lancer votre projet', 'hero.cta2': 'Usine & export',
    's1.title': 'Solutions pour quatre secteurs clés',
    's1.p': 'Chaque secteur a ses exigences électriques, thermiques et mécaniques — notre équipe d\u2019ingénierie vous aide à choisir la bonne construction du premier coup.',
    's1.c1t': 'Projets éoliens', 's1.c1d': 'Câbles MT tour-réseau à conducteurs souples, excellente résistance au froid et aux UV, terminaisons fiables.',
    's1.c2t': 'Centrales solaires', 's1.c2d': 'Chaînes PV, circuits DC et câbles de collecte MT à haute tenue en température et longue durée de vie.',
    's1.c3t': 'Data centers & calcul IA', 's1.c3d': 'Câbles d\u2019alimentation 35 kV haute puissance pour clusters IA — faibles pertes, ignifuges, évolutifs.',
    's1.c4t': 'Industrie & mines', 's1.c4d': 'Câbles armés pour environnements sévères : résistance à l\u2019abrasion, aux huiles et à l\u2019humidité.',
    's2.title': 'Périmètre des solutions par secteur',
    's2.p': 'De l\u2019ingénierie de projet aux conseils d\u2019installation — le périmètre complet couvert pour chaque secteur.',
    's2.th1': 'Secteur', 's2.th2': 'Types de câbles', 's2.th3': 'Accessoires', 's2.th4': 'Support',
    's2.r1c1': 'Éolien', 's2.r1c2': 'MT souples 12/20, 26/35 kV', 's2.r1c3': 'Extrémités, kits de jonction', 's2.r1c4': 'Calcul de tracé et d\u2019ampérage',
    's2.r2c1': 'Solaire', 's2.r2c2': 'PV1-F, câbles DC, collecte MT', 's2.r2c3': 'Connecteurs DC, mise à la terre', 's2.r2c4': 'Conseils de conception',
    's2.r3c1': 'Data center / IA', 's2.r3c2': 'Départs 35 kV LSZH, contrôle', 's2.r3c3': 'Jonctions bus, supervision', 's2.r3c4': 'Redondance & sécurité incendie',
    's2.r4c1': 'Mines & industrie', 's2.r4c2': 'Armés SWA, câbles caoutchouc', 's2.r4c3': 'Presse-étoupes, connecteurs', 's2.r4c4': 'Renforcement spécifique site',
    's3.title': 'Comment fonctionne une fourniture projet',
    's3.p': 'Un parcours structuré, de votre demande à l\u2019installation — accompagné à chaque étape.',
    's3.s1t': 'Demande projet', 's3.s1d': 'Partagez plans, tension et charges — nos ingénieurs confirment le calendrier câbles.',
    's3.s2t': 'Solution & devis', 's3.s2d': 'Calendrier câbles, liste d\u2019accessoires et devis usine livrés ensemble.',
    's3.s3t': 'Production & contrôle', 's3.s3d': 'Fabrication et essais ; photos, rapports et inspection témoin disponibles.',
    's3.s4t': 'Logistique & douane', 's3.s4d': 'Documentation export, expédition et support douanier à destination.',
    's3.s5t': 'Support installation', 's3.s5d': 'Conseils de jonction et d\u2019extrémités par ingénieurs expérimentés, à distance ou sur site.',
    's4.title': 'Support ingénierie inclus',
    's4.p': 'Chaque fourniture projet inclut l\u2019aide au choix des câbles, la vérification de section et de chute de tension, le choix des accessoires et les conseils d\u2019installation. Envoyez plans et charges — nos ingénieurs préparent le calendrier câbles.',
    'faq.title': 'FAQ — solutions projets',
    'faq.q1': 'Fournissez-vous le calendrier câbles complet ?', 'faq.a1': 'Oui — partagez vos plans et charges, nous proposons le calendrier câbles et accessoires complet.',
    'faq.q2': 'Fournissez-vous kits de jonction et extrémités ?', 'faq.a2': 'Oui — kits compatibles fournis avec les câbles, adaptés à la classe de tension et au conducteur.',
    'faq.q3': 'Aidez-vous au dimensionnement ?', 'faq.a3': 'Oui — nos ingénieurs fournissent gratuitement le choix de section, la vérification de chute de tension et d\u2019ampérage.',
    'faq.q4': 'Assurez-vous l\u2019installation sur site ?', 'faq.a4': 'Conseils d\u2019installation et de jonction à distance, ou ingénieurs sur site pour grands projets.',
    'faq.q5': 'Et les câbles de rechange ?', 'faq.a5': 'Nous recommandons de commander des tourets de rechange avec l\u2019envoi principal — les commandes supplémentaires sont produites rapidement.',
    'cta.title': 'Lancez votre projet câbles aujourd\u2019hui',
    'cta.p': 'Envoyez plans et exigences — nos équipes répondent sous 24 h avec une solution complète et un devis.',
}

I18N['de'] = {
    'hero.eyebrow': 'Schlüsselfertige Lieferung · Engineering-Support · 2026',
    'hero.title': 'Komplette Kabellösungen für <span class="accent">Energie, Rechenzentren & Industrie</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — eine Quelle für Kabel, Zubehör & Support',
    'hero.lead': 'Eine Anfrage, eine Lieferkette: Mittelspannungskabel, Zubehör, Muffen-Beratung und Engineering-Support für Windparks, Solaranlagen, Rechenzentren und Industrieprojekte — pünktlich, weltweit.',
    'hero.cta1': 'Projekt starten', 'hero.cta2': 'Werk & Export',
    's1.title': 'Lösungen für vier Kernsektoren',
    's1.p': 'Jeder Sektor hat eigene elektrische, thermische und mechanische Anforderungen — unser Engineering-Team hilft Ihnen, die richtige Kabelkonstruktion auf Anhieb zu wählen.',
    's1.c1t': 'Windkraftprojekte', 's1.c1d': 'MS-Kabel vom Turm zum Netz mit flexiblen Leitern, exzellenter Kälte- und UV-Beständigkeit.',
    's1.c2t': 'Solar-PV-Anlagen', 's1.c2d': 'PV-Stränge, DC-Kreise und MS-Sammelkabel mit hoher Umgebungstemperatur-Beständigkeit.',
    's1.c3t': 'Rechenzentren & KI-Computing', 's1.c3d': 'Hochleistungs-35-kV-Speisekabel für KI-Cluster — verlustarm, flammwidrig, zukunftssicher.',
    's1.c4t': 'Industrie & Bergbau', 's1.c4d': 'Armierte Kabel für raue Umgebungen: abrasions-, öl- und feuchtigkeitsbeständig.',
    's2.title': 'Lösungsumfang je Sektor',
    's2.p': 'Von der Projektplanung bis zur Installationsberatung — der komplette Umfang für jeden Sektor.',
    's2.th1': 'Sektor', 's2.th2': 'Kabeltypen', 's2.th3': 'Zubehör', 's2.th4': 'Support',
    's2.r1c1': 'Wind', 's2.r1c2': 'Flexibel 12/20, 26/35 kV', 's2.r1c3': 'Endverschlüsse, Muffensätze', 's2.r1c4': 'Trassen- & Lastberechnung',
    's2.r2c1': 'Solar', 's2.r2c2': 'PV1-F, DC-Kabel, MS-Sammel', 's2.r2c3': 'DC-Stecker, Erdung', 's2.r2c4': 'Designberatung',
    's2.r3c1': 'Rechenzentrum / KI', 's2.r3c2': '35 kV LSZH-Abgänge, Steuer', 's2.r3c3': 'Busverbindungen, Überwachung', 's2.r3c4': 'Redundanz & Brandschutz',
    's2.r4c1': 'Bergbau & Industrie', 's2.r4c2': 'Armiert SWA, Gummi', 's2.r4c3': 'Verschraubungen, Kupplungen', 's2.r4c4': 'Standortspezifische Härtung',
    's3.title': 'So läuft eine Projektlieferung ab',
    's3.p': 'Ein strukturierter Weg von Ihrer Anfrage bis zur Installation — mit Unterstützung in jedem Schritt.',
    's3.s1t': 'Projektanfrage', 's3.s1d': 'Teilen Sie Pläne, Spannung und Lastdaten — Ingenieure bestätigen die Kabelübersicht.',
    's3.s2t': 'Lösung & Angebot', 's3.s2d': 'Kabelübersicht, Zubehörliste und Werksangebot zusammen.',
    's3.s3t': 'Produktion & Prüfung', 's3.s3d': 'Fertigung und Prüfung; Fotos, Berichte und Zeugenprüfung verfügbar.',
    's3.s4t': 'Logistik & Zoll', 's3.s4d': 'Exportdokumentation, Versand und Zollunterstützung.',
    's3.s5t': 'Installationssupport', 's3.s5d': 'Muffen- und Endverschluss-Beratung durch erfahrene Ingenieure, remote oder vor Ort.',
    's4.title': 'Engineering-Support inklusive',
    's4.p': 'Jede Projektlieferung umfasst Kabelauswahlhilfe, Querschnitts- und Spannungsfallprüfung, Zubehörabstimmung und Installationsberatung. Senden Sie Pläne und Lastdaten — wir erstellen die Kabelübersicht.',
    'faq.title': 'FAQ — Projektlösungen',
    'faq.q1': 'Liefern Sie die komplette Kabelübersicht?', 'faq.a1': 'Ja — teilen Sie Projektpläne und Lastdaten, wir schlagen die vollständige Kabel- und Zubehörliste vor.',
    'faq.q2': 'Liefern Sie Muffen- und Endverschlusssätze?', 'faq.a2': 'Ja — kompatible Sätze werden mit den Kabeln geliefert, passend zu Spannungsklasse und Leiter.',
    'faq.q3': 'Helfen Sie bei der Kabeldimensionierung?', 'faq.a3': 'Ja — kostenlose Querschnittswahl, Spannungsfall- und Stromtragfähigkeitsprüfung.',
    'faq.q4': 'Unterstützen Sie die Installation vor Ort?', 'faq.a4': 'Installations- und Muffenberatung remote oder mit Ingenieuren vor Ort bei größeren Projekten.',
    'faq.q5': 'Und Ersatzkabel für die Wartung?', 'faq.a5': 'Wir empfehlen Ersatztrommeln mit der Hauptlieferung — Folgeaufträge werden schnell produziert.',
    'cta.title': 'Starten Sie Ihr Kabelprojekt noch heute',
    'cta.p': 'Senden Sie Pläne und Anforderungen — unsere Teams antworten innerhalb von 24 Stunden mit kompletter Lösung und Angebot.',
}

I18N['uk'] = {
    'hero.eyebrow': 'Комплексні поставки · Інженерна підтримка · 2026',
    'hero.title': 'Повні кабельні рішення для <span class="accent">енергетики, ЦОД і промисловості</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — єдине джерело: кабель, аксесуари та підтримка',
    'hero.lead': 'Один запит — один ланцюг поставок: кабелі середньої напруги, аксесуари, рекомендації з монтажу та інженерна підтримка для вітропарків, сонячних станцій, ЦОД і промислових проєктів — вчасно, по всьому світу.',
    'hero.cta1': 'Почати проєкт', 'hero.cta2': 'Завод та експорт',
    's1.title': 'Рішення для чотирьох ключових секторів',
    's1.p': 'У кожного сектора свої електричні, теплові та механічні вимоги — наша інженерна команда допоможе обрати правильну конструкцію кабелю з першого разу.',
    's1.c1t': 'Вітроенергетика', 's1.c1d': 'Кабелі СН від вежі до мережі: гнучкі жили, чудова стійкість до холоду та УФ, надійне оконцювання.',
    's1.c2t': 'Сонячні електростанції', 's1.c2d': 'PV-ланцюги, кола постійного струму та кабелі СН з високою робочою температурою і тривалим терміном служби.',
    's1.c3t': 'ЦОД та ІІ-обчислення', 's1.c3d': 'Потужні живильні кабелі 35 кВ для ІІ-кластерів — низькі втрати, вогнестійкість, готовність до майбутнього.',
    's1.c4t': 'Промисловість і гірництво', 's1.c4d': 'Броньовані кабелі для жорстких умов: стійкість до стирання, оливи та вологи.',
    's2.title': 'Обсяг рішень за секторами',
    's2.p': 'Від проєктування до шеф-монтажу — повний обсяг для кожного сектора.',
    's2.th1': 'Сектор', 's2.th2': 'Типи кабелів', 's2.th3': 'Аксесуари', 's2.th4': 'Підтримка',
    's2.r1c1': 'Вітер', 's2.r1c2': 'Гнучкі 12/20, 26/35 кВ', 's2.r1c3': 'Оконцювання, муфти', 's2.r1c4': 'Розрахунок траси та струму',
    's2.r2c1': 'Сонце', 's2.r2c2': 'PV1-F, кабелі DC, СН', 's2.r2c3': 'DC-конектори, заземлення', 's2.r2c4': 'Рекомендації з проєктування',
    's2.r3c1': 'ЦОД / ІІ', 's2.r3c2': '35 кВ LSZH, контрольні', 's2.r3c3': 'Шинопроводи, моніторинг', 's2.r3c4': 'Резервування та пожежна безпека',
    's2.r4c1': 'Гірництво та пром.', 's2.r4c2': 'Броньовані SWA, гумові', 's2.r4c3': 'Кабельні вводи, з\u2019єднувачі', 's2.r4c4': 'Посилення під об\u2019єкт',
    's3.title': 'Як працюють проєктні поставки',
    's3.p': 'Структурований шлях від запиту до монтажу — підтримка на кожному кроці.',
    's3.s1t': 'Проєктний запит', 's3.s1d': 'Надішліть креслення, напругу та навантаження — інженери підтвердять кабельну відомість.',
    's3.s2t': 'Рішення та котирування', 's3.s2d': 'Кабельна відомість, список аксесуарів і котирування заводу — разом.',
    's3.s3t': 'Виробництво та контроль', 's3.s3d': 'Виготовлення та випробування; фото, звіти, присутність при контролі.',
    's3.s4t': 'Логістика та митниця', 's3.s4d': 'Експортна документація, доставка та митна підтримка.',
    's3.s5t': 'Шеф-монтаж', 's3.s5d': 'Рекомендації з монтажу муфт та оконцювань, дистанційно або на об\u2019єкті.',
    's4.title': 'Інженерна підтримка включена',
    's4.p': 'Кожна поставка включає допомогу з вибором кабелю, перевірку перерізу та падіння напруги, підбір аксесуарів і рекомендації з монтажу. Надішліть креслення та дані навантажень — інженери підготують кабельну відомість.',
    'faq.title': 'Питання та відповіді — проєктні рішення',
    'faq.q1': 'Чи можете поставити повну кабельну відомість?', 'faq.a1': 'Так — надішліть креслення та дані навантажень, запропонуємо повну відомість кабелів та аксесуарів.',
    'faq.q2': 'Чи постачаєте муфти та оконцювання?', 'faq.a2': 'Так — сумісні комплекти муфт та оконцювань постачаються з кабелем, під клас напруги та переріз.',
    'faq.q3': 'Чи допомагаєте з вибором перерізу?', 'faq.a3': 'Так — інженери безкоштовно виконають підбір перерізу, перевірку падіння напруги та струмового навантаження.',
    'faq.q4': 'Чи підтримуєте монтаж на об\u2019єкті?', 'faq.a4': 'Надаємо рекомендації з монтажу та з\u2019єднання дистанційно; для великих проєктів — інженери на об\u2019єкті.',
    'faq.q5': 'Як замовити резервні кабелі?', 'faq.a5': 'Рекомендуємо замовляти резервні барабани з основною партією; додаткові замовлення виробляються швидко.',
    'cta.title': 'Почніть свій кабельний проєкт сьогодні',
    'cta.p': 'Надішліть креслення та вимоги — інженерна та експортна команди дадуть відповідь протягом 24 годин з повним рішенням і котируванням.',
}

I18N['es'] = {
    'hero.eyebrow': 'Suministro integral · Soporte de ingeniería · 2026',
    'hero.title': 'Soluciones de cable completas para <span class="accent">energía, centros de datos e industria</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — una sola fuente para cable, accesorios y soporte',
    'hero.lead': 'Una consulta, una cadena de suministro: cables de media tensión, accesorios, guía de empalmes y soporte de ingeniería para parques eólicos, plantas solares, centros de datos y proyectos industriales — entregado a tiempo, en todo el mundo.',
    'hero.cta1': 'Iniciar su proyecto', 'hero.cta2': 'Fábrica y exportación',
    's1.title': 'Soluciones en cuatro sectores clave',
    's1.p': 'Cada sector tiene exigencias eléctricas, térmicas y mecánicas propias — nuestro equipo de ingeniería lo ayuda a elegir la construcción de cable correcta a la primera.',
    's1.c1t': 'Proyectos eólicos', 's1.c1d': 'Cables MT de torre a red con conductores flexibles, excelente resistencia al frío y a los rayos UV.',
    's1.c2t': 'Plantas solares', 's1.c2d': 'Cadenas PV, circuitos DC y cables de recolección MT con alta temperatura ambiente y larga vida útil.',
    's1.c3t': 'Centros de datos y cómputo IA', 's1.c3d': 'Cables de alimentación de 35 kV de alta potencia para clústeres IA — baja pérdida, retardantes de llama, a prueba de futuro.',
    's1.c4t': 'Industria y minería', 's1.c4d': 'Cables armados para entornos severos: resistentes a abrasión, aceite y humedad.',
    's2.title': 'Alcance de soluciones por sector',
    's2.p': 'De la ingeniería de proyecto a la guía de instalación — el alcance completo que cubrimos en cada sector.',
    's2.th1': 'Sector', 's2.th2': 'Tipos de cable', 's2.th3': 'Extras', 's2.th4': 'Soporte',
    's2.r1c1': 'Eólico', 's2.r1c2': 'MT flexibles 12/20, 26/35 kV', 's2.r1c3': 'Terminales, kits de empalme', 's2.r1c4': 'Cálculo de trazado y carga',
    's2.r2c1': 'Solar', 's2.r2c2': 'PV1-F, cables DC, recolección MT', 's2.r2c3': 'Conectores DC, puesta a tierra', 's2.r2c4': 'Asesoría de diseño',
    's2.r3c1': 'Data center / IA', 's2.r3c2': 'Alimentadores 35 kV LSZH, control', 's2.r3c3': 'Conexiones de barra, monitoreo', 's2.r3c4': 'Redundancia y seguridad contra incendios',
    's2.r4c1': 'Minería e industria', 's2.r4c2': 'Armados SWA, cables de goma', 's2.r4c3': 'Prensaestopas, acopladores', 's2.r4c4': 'Refuerzo específico del sitio',
    's3.title': 'Cómo funciona un suministro de proyecto',
    's3.p': 'Un camino estructurado de su consulta a la instalación — con soporte en cada paso.',
    's3.s1t': 'Consulta de proyecto', 's3.s1d': 'Comparta planos, voltaje y datos de carga — nuestros ingenieros confirman el cronograma de cable.',
    's3.s2t': 'Solución y cotización', 's3.s2d': 'Cronograma de cable, lista de accesorios y cotización de fábrica juntos.',
    's3.s3t': 'Producción e inspección', 's3.s3d': 'Fabricación y ensayos; fotos, informes e inspección testimonial disponibles.',
    's3.s4t': 'Logística y aduanas', 's3.s4d': 'Documentación de exportación, envío y soporte aduanero a su destino.',
    's3.s5t': 'Soporte de instalación', 's3.s5d': 'Guía de empalmes y terminales por ingenieros experimentados, remota o en sitio.',
    's4.title': 'Soporte de ingeniería incluido',
    's4.p': 'Cada suministro de proyecto incluye asistencia de selección de cable, verificación de sección y caída de voltaje, emparejamiento de accesorios y guía de instalación. Envíe sus planos y datos de carga — nuestros ingenieros prepararán el cronograma de cable.',
    'faq.title': 'FAQ — soluciones de proyecto',
    'faq.q1': '¿Pueden suministrar el cronograma de cable completo?', 'faq.a1': 'Sí — comparta sus planos y datos de carga, propondremos el cronograma completo de cable y accesorios.',
    'faq.q2': '¿Proveen kits de empalme y terminales?', 'faq.a2': 'Sí — kits compatibles se suministran con los cables, acordes a la clase de voltaje y al conductor.',
    'faq.q3': '¿Ayudan con el dimensionamiento del cable?', 'faq.a3': 'Sí — nuestros ingenieros brindan selección de sección, verificación de caída de voltaje y ampacidad sin costo.',
    'faq.q4': '¿Apoyan la instalación en sitio?', 'faq.a4': 'Brindamos guía de instalación y empalmes remota o con ingenieros en sitio para proyectos grandes.',
    'faq.q5': '¿Y los cables de repuesto para mantenimiento?', 'faq.a5': 'Recomendamos pedir bobinas de repuesto con el envío principal — los pedidos adicionales se producen rápido.',
    'cta.title': 'Inicie su proyecto de cable hoy',
    'cta.p': 'Envíe sus planos y requisitos — nuestros equipos de ingeniería y exportación responderán en 24 horas con solución completa y cotización.',
}

I18N['tr'] = {
    'hero.eyebrow': 'Anahtar Teslim Tedarik · Mühendislik Desteği · 2026',
    'hero.title': '<span class="accent">Enerji, Veri Merkezi ve Sanayi</span> için Eksiksiz Kablo Çözümleri',
    'hero.sub': 'OUZHI Cable (欧智电缆) — Kablo, Aksesuar ve Destek için Tek Kaynak',
    'hero.lead': 'Tek talep, tek tedarik zinciri: rüzgar santralleri, güneş santralleri, veri merkezleri ve endüstriyel projeler için orta gerilim kabloları, aksesuarlar, ek bağlantı rehberliği ve mühendislik desteği — zamanında, dünya genelinde.',
    'hero.cta1': 'Projenizi Başlatın', 'hero.cta2': 'Fabrika ve İhracat',
    's1.title': 'Dört Temel Sektörde Çözümler',
    's1.p': 'Her sektörün kendi elektriksel, termal ve mekanik gereksinimleri vardır — mühendislik ekibimiz doğru kablo yapısını ilk seferde seçmenize yardımcı olur.',
    's1.c1t': 'Rüzgar Enerjisi Projeleri', 's1.c1d': 'Kuleden şebekeye esnek iletkenli OG kablolar, mükemmel soğuk ve UV dayanımı.',
    's1.c2t': 'Güneş Santralleri', 's1.c2d': 'PV dizileri, DC devreleri ve yüksek ortam sıcaklığına dayanıklı OG toplama kabloları.',
    's1.c3t': 'Veri Merkezleri ve Yapay Zeka', 's1.c3d': 'Yapay zeka kümeleri için yüksek güçlü 35 kV besleme kabloları — düşük kayıp, alev geciktirici.',
    's1.c4t': 'Sanayi ve Madencilik', 's1.c4d': 'Zorlu ortamlar için zırhlı kablolar: aşınmaya, yağa ve neme dayanıklı.',
    's2.title': 'Sektör Bazında Çözüm Kapsamı',
    's2.p': 'Proje mühendisliğinden kurulum rehberliğine — her sektör için kapsadığımız tam kapsam.',
    's2.th1': 'Sektör', 's2.th2': 'Kablo Tipleri', 's2.th3': 'Ek Donanım', 's2.th4': 'Destek',
    's2.r1c1': 'Rüzgar', 's2.r1c2': 'Esnek 12/20, 26/35 kV OG', 's2.r1c3': 'Sonlandırma, ek kitleri', 's2.r1c4': 'Güzergah ve akım hesabı',
    's2.r2c1': 'Güneş', 's2.r2c2': 'PV1-F, DC kablolar, OG toplama', 's2.r2c3': 'DC konnektörler, topraklama', 's2.r2c4': 'Dizi ve santral tasarımı',
    's2.r3c1': 'Veri Merkezi / YZ', 's2.r3c2': '35 kV LSZH beslemeler, kontrol', 's2.r3c3': 'Baralar, izleme', 's2.r3c4': 'Yedeklilik ve yangın güvenliği',
    's2.r4c1': 'Madencilik ve Sanayi', 's2.r4c2': 'Zırhlı SWA, kauçuk kablolar', 's2.r4c3': 'Rakorlar, bağlaçlar', 's2.r4c4': 'Sahaya özel güçlendirme',
    's3.title': 'Proje Tedariki Nasıl Çalışır',
    's3.p': 'Talebinizden saha kurulumuna yapılandırılmış bir yol — her adımda destekli.',
    's3.s1t': 'Proje Talebi', 's3.s1d': 'Çizimleri, gerilimi ve yük verilerini paylaşın — mühendisler kablo listesini onaylar.',
    's3.s2t': 'Çözüm ve Teklif', 's3.s2d': 'Kablo listesi, aksesuar listesi ve fabrika teklifi birlikte sunulur.',
    's3.s3t': 'Üretim ve Muayene', 's3.s3d': 'Üretim ve test; fotoğraf, rapor ve tanıklı muayene mevcuttur.',
    's3.s4t': 'Lojistik ve Gümrük', 's3.s4d': 'İhracat dokümantasyonu, sevkiyat ve varış ülkesi gümrük desteği.',
    's3.s5t': 'Kurulum Desteği', 's3.s5d': 'Deneyimli mühendislerden uzaktan veya sahada ek ve sonlandırma rehberliği.',
    's4.title': 'Mühendislik Desteği Dahil',
    's4.p': 'Her proje tedariki kablo seçimi yardımı, kesit ve gerilim düşümü kontrolü, aksesuar eşleştirme ve kurulum rehberliği içerir. Çizimlerinizi ve yük verilerinizi gönderin — mühendislerimiz kablo listenizi hazırlasın.',
    'faq.title': 'SSS — Proje Çözümleri',
    'faq.q1': 'Komple kablo listesi tedarik edebilir misiniz?', 'faq.a1': 'Evet — proje çizimlerinizi ve yük verilerinizi paylaşın, tam kablo ve aksesuar listesi önerelim.',
    'faq.q2': 'Ek ve sonlandırma kitleri sağlıyor musunuz?', 'faq.a2': 'Evet — gerilim sınıfı ve iletkene uygun uyumlu ek ve sonlandırma kitleri kablolarla birlikte verilir.',
    'faq.q3': 'Kablo boyutlandırmaya yardımcı oluyor musunuz?', 'faq.a3': 'Evet — mühendislerimiz kesit seçimi, gerilim düşümü ve akım taşıma kontrolünü ücretsiz sağlar.',
    'faq.q4': 'Saha kurulumunu destekliyor musunuz?', 'faq.a4': 'Kurulum ve ek rehberliğini uzaktan veya büyük projelerde sahada mühendislerle sağlarız.',
    'faq.q5': 'Peki bakım için yedek kablolar?', 'faq.a5': 'Ana sevkiyatla birlikte yedek makara sipariş etmenizi öneririz — ek siparişler hatlarımızdan hızla üretilir.',
    'cta.title': 'Kablo Projenizi Bugün Başlatın',
    'cta.p': 'Çizimlerinizi ve gereksinimlerinizi gönderin — mühendislik ve ihracat ekiplerimiz 24 saat içinde eksiksiz çözüm ve teklifle yanıtlar.',
}

I18N['pt'] = {
    'hero.eyebrow': 'Fornecimento completo · Suporte de engenharia · 2026',
    'hero.title': 'Soluções completas de cabos para <span class="accent">energia, data centers e indústria</span>',
    'hero.sub': 'OUZHI Cable (欧智电缆) — uma única fonte para cabos, acessórios e suporte',
    'hero.lead': 'Uma consulta, uma cadeia de suprimentos: cabos de média tensão, acessórios, orientação de emendas e suporte de engenharia para parques eólicos, usinas solares, data centers e projetos industriais — entregue no prazo, em todo o mundo.',
    'hero.cta1': 'Iniciar seu projeto', 'hero.cta2': 'Fábrica e exportação',
    's1.title': 'Soluções em quatro setores centrais',
    's1.p': 'Cada setor tem suas exigências elétricas, térmicas e mecânicas — nossa equipe de engenharia ajuda você a escolher a construção de cabo certa na primeira vez.',
    's1.c1t': 'Projetos eólicos', 's1.c1d': 'Cabos MT de torre à rede com condutores flexíveis, excelente resistência ao frio e aos raios UV.',
    's1.c2t': 'Usinas solares', 's1.c2d': 'Strings PV, circuitos DC e cabos de coleta MT com alta temperatura ambiente e longa vida útil.',
    's1.c3t': 'Data centers e computação IA', 's1.c3d': 'Cabos alimentadores de 35 kV de alta potência para clusters de IA — baixa perda, retardantes de chama, à prova do futuro.',
    's1.c4t': 'Indústria e mineração', 's1.c4d': 'Cabos armados para ambientes severos: resistentes à abrasão, óleo e umidade.',
    's2.title': 'Escopo de soluções por setor',
    's2.p': 'Da engenharia de projeto à orientação de instalação — o escopo completo que cobrimos em cada setor.',
    's2.th1': 'Setor', 's2.th2': 'Tipos de cabo', 's2.th3': 'Extras', 's2.th4': 'Suporte',
    's2.r1c1': 'Eólico', 's2.r1c2': 'MT flexíveis 12/20, 26/35 kV', 's2.r1c3': 'Terminais, kits de emenda', 's2.r1c4': 'Cálculo de traçado e carga',
    's2.r2c1': 'Solar', 's2.r2c2': 'PV1-F, cabos DC, coleta MT', 's2.r2c3': 'Conectores DC, aterramento', 's2.r2c4': 'Consultoria de projeto',
    's2.r3c1': 'Data center / IA', 's2.r3c2': 'Alimentadores 35 kV LSZH, controle', 's2.r3c3': 'Conexões de barramento, monitoramento', 's2.r3c4': 'Redundância e segurança contra incêndio',
    's2.r4c1': 'Mineração e indústria', 's2.r4c2': 'Armados SWA, cabos de borracha', 's2.r4c3': 'Preensaelos, acopladores', 's2.r4c4': 'Reforço específico do local',
    's3.title': 'Como funciona um fornecimento de projeto',
    's3.p': 'Um caminho estruturado da sua consulta à instalação — com suporte em cada etapa.',
    's3.s1t': 'Consulta de projeto', 's3.s1d': 'Compartilhe desenhos, tensão e dados de carga — nossos engenheiros confirmam o cronograma de cabos.',
    's3.s2t': 'Solução e cotação', 's3.s2d': 'Cronograma de cabos, lista de acessórios e cotação de fábrica juntos.',
    's3.s3t': 'Produção e inspeção', 's3.s3d': 'Fabricação e ensaios; fotos, relatórios e inspeção testemunhal disponíveis.',
    's3.s4t': 'Logística e alfândega', 's3.s4d': 'Documentação de exportação, envio e suporte aduaneiro ao seu destino.',
    's3.s5t': 'Suporte de instalação', 's3.s5d': 'Orientação de emendas e terminais por engenheiros experientes, remota ou no local.',
    's4.title': 'Suporte de engenharia incluído',
    's4.p': 'Cada fornecimento de projeto inclui assistência na seleção de cabos, verificação de seção e queda de tensão, combinação de acessórios e orientação de instalação. Envie seus desenhos e dados de carga — nossos engenheiros prepararão o cronograma de cabos.',
    'faq.title': 'FAQ — soluções de projeto',
    'faq.q1': 'Vocês fornecem o cronograma completo de cabos?', 'faq.a1': 'Sim — compartilhe seus desenhos e dados de carga, proporemos o cronograma completo de cabos e acessórios.',
    'faq.q2': 'Vocês fornecem kits de emenda e terminais?', 'faq.a2': 'Sim — kits compatíveis são fornecidos com os cabos, adequados à classe de tensão e ao condutor.',
    'faq.q3': 'Vocês ajudam no dimensionamento do cabo?', 'faq.a3': 'Sim — nossos engenheiros fornecem seleção de seção, verificação de queda de tensão e ampacidade sem custo.',
    'faq.q4': 'Vocês apoiam a instalação no local?', 'faq.a4': 'Fornecemos orientação de instalação e emendas remota ou com engenheiros no local para projetos grandes.',
    'faq.q5': 'E cabos sobressalentes para manutenção?', 'faq.a5': 'Recomendamos pedir bobinas sobressalentes com o envio principal — pedidos adicionais são produzidos rapidamente.',
    'cta.title': 'Inicie seu projeto de cabos hoje',
    'cta.p': 'Envie seus desenhos e requisitos — nossas equipes de engenharia e exportação responderão em 24 horas com solução completa e cotação.',
}

I18N['mn'] = {
    'hero.eyebrow': 'Цогц нийлүүлэлт · Инженерийн дэмжлэг · 2026',
    'hero.title': '<span class="accent">Эрчим хүч, өгөгдлийн төв, аж үйлдвэр</span>д зориулсан бүрэн кабелийн шийдэл',
    'hero.sub': 'OUZHI Cable (欧智电缆) — кабель, дагалдах хэрэгсэл, дэмжлэгийн нэгдсэн эх үүсвэр',
    'hero.lead': 'Нэг асуулт, нэг нийлүүлэлтийн сүлжээ: салхин парк, нарны станц, өгөгдлийн төв, аж үйлдвэрийн төсөлд зориулсан дундад хүчдэлийн кабель, дагалдах хэрэгсэл, холболтын зөвлөгөө, инженерийн дэмжлэг — цаг хугацаанд нь, дэлхий даяар.',
    'hero.cta1': 'Төслөө эхлүүлэх', 'hero.cta2': 'Үйлдвэр ба экспорт',
    's1.title': 'Дөрвөн үндсэн салбарын шийдэл',
    's1.p': 'Салбар бүр өөрийн цахилгаан, дулаан, механик шаардлагатай — манай инженерийн баг зөв кабелийн бүтцийг анхнаасаа сонгоход тань туслана.',
    's1.c1t': 'Салхин эрчим хүчний төсөл', 's1.c1d': 'Цамхагаас сүлжээнд хүргэх уян дамжуулагчтай ДХ кабель, хүйтэн, хэт ягаан туяанд тэсвэртэй.',
    's1.c2t': 'Нарны станц', 's1.c2d': 'PV цуваа, тогтмол гүйдлийн хэлхээ, өндөр температурын ДХ коллекцийн кабель.',
    's1.c3t': 'Өгөгдлийн төв ба AI тооцоолол', 's1.c3d': 'AI бүлгэмд зориулсан өндөр хүчин чадлын 35 кВ тэжээлийн кабель — бага алдагдал, галд тэсвэртэй.',
    's1.c4t': 'Аж үйлдвэр ба уул уурхай', 's1.c4d': 'Хэцүү орчинд зориулсан хуягласан кабель: элэгдэл, тос, чийгэнд тэсвэртэй.',
    's2.title': 'Салбар бүрийн шийдлийн хамрах хүрээ',
    's2.p': 'Төслийн инженерчлэлээс суурилуулалтын зөвлөгөө хүртэл — салбар бүрт хамрах бүрэн хүрээ.',
    's2.th1': 'Салбар', 's2.th2': 'Кабелийн төрөл', 's2.th3': 'Дагалдах', 's2.th4': 'Дэмжлэг',
    's2.r1c1': 'Салхи', 's2.r1c2': 'Уян 12/20, 26/35 кВ', 's2.r1c3': 'Терминал, холболтын иж бүрдэл', 's2.r1c4': 'Замын болон ачааллын тооцоо',
    's2.r2c1': 'Нар', 's2.r2c2': 'PV1-F, DC кабель, ДХ коллекц', 's2.r2c3': 'DC холбогч, газардуулга', 's2.r2c4': 'Дизайн зөвлөгөө',
    's2.r3c1': 'Өгөгдлийн төв / AI', 's2.r3c2': '35 кВ LSZH тэжээл, удирдлага', 's2.r3c3': 'Шинний холболт, мониторинг', 's2.r3c4': 'Илүүдэл ба галын аюулгүй байдал',
    's2.r4c1': 'Уул уурхай ба аж үйлдвэр', 's2.r4c2': 'Хуягласан SWA, резинэн кабель', 's2.r4c3': 'Кабелийн бэхэлгээ, холбогч', 's2.r4c4': 'Талбайд тохирсон бэхжүүлэлт',
    's3.title': 'Төслийн нийлүүлэлт хэрхэн ажилладаг вэ',
    's3.p': 'Таны асуултаас талбайн суурилуулалт хүртэлх бүтэцтэй зам — алхам бүрт дэмжлэгтэй.',
    's3.s1t': 'Төслийн асуулт', 's3.s1d': 'Зураг, хүчдэл, ачааллын өгөгдлөө хуваалцана уу — инженерүүд кабелийн жагсаалтыг баталгаажуулна.',
    's3.s2t': 'Шийдэл ба үнэ', 's3.s2d': 'Кабелийн жагсаалт, дагалдах хэрэгслийн жагсаалт, үйлдвэрийн үнэ хамт өгөгдөнө.',
    's3.s3t': 'Үйлдвэрлэл ба хяналт', 's3.s3d': 'Кабель үйлдвэрлэж, шалгана; зураг, тайлан, гэрчийн хяналт боломжтой.',
    's3.s4t': 'Логистик ба гааль', 's3.s4d': 'Экспортын баримт, тээвэр, очих газрын гаалийн дэмжлэг.',
    's3.s5t': 'Суурилуулалтын дэмжлэг', 's3.s5d': 'Туршлагатай инженерүүдээс холболт, терминалын зөвлөгөө — алсаас эсвэл талбайд.',
    's4.title': 'Инженерийн дэмжлэг багтсан',
    's4.p': 'Төслийн нийлүүлэлт бүрт кабель сонголтын туслалцаа, хөндлөн огтлол ба хүчдэлийн уналтын шалгалт, дагалдах хэрэгслийн тохируулга, суурилуулалтын зөвлөгөө багтана. Зураг, ачааллын өгөгдлөө илгээнэ үү — инженерүүд кабелийн жагсаалтыг бэлтгэнэ.',
    'faq.title': 'Түгээмэл асуулт — төслийн шийдэл',
    'faq.q1': 'Бүрэн кабелийн жагсаалтыг нийлүүлж чадах уу?', 'faq.a1': 'Тийм — төслийн зураг, ачааллын өгөгдлөө хуваалцана уу, бүрэн кабель ба дагалдах хэрэгслийн жагсаалтыг санал болгоно.',
    'faq.q2': 'Холболт, терминалын иж бүрдэл өгдөг үү?', 'faq.a2': 'Тийм — хүчдэлийн ангилал, дамжуулагчид тохирсон иж бүрдэл кабельтэй хамт нийлүүлэгдэнэ.',
    'faq.q3': 'Кабель хэмжээст туслах уу?', 'faq.a3': 'Тийм — инженерүүд хөндлөн огтлол, хүчдэлийн уналт, гүйдэл даах чадварын шалгалтыг үнэгүй хийж өгнө.',
    'faq.q4': 'Талбай дээрх суурилуулалтыг дэмждэг үү?', 'faq.a4': 'Суурилуулалт, холболтын зөвлөгөөг алсаас; том төслүүдэд талбай дээрх инженерээр дэмжинэ.',
    'faq.q5': 'Засварын нөөц кабель яах вэ?', 'faq.a5': 'Үндсэн ачаатай хамт нөөц ороомог захиалахыг зөвлөнө — нэмэлт захиалгыг шугамаасаа хурдан үйлдвэрлэнэ.',
    'cta.title': 'Кабелийн төслөө өнөөдөр эхлүүлээрэй',
    'cta.p': 'Зураг, шаардлагаа илгээнэ үү — инженерийн ба экспортын баг 24 цагийн дотор бүрэн шийдэл, үнэтэй хариу өгнө.',
}
